- pkg/ip/link.go
- plugins/ipam/host-local/main.go
- plugins/main/bridge/bridge.go
- plugins/main/ipvlan/ipvlan.go
- plugins/main/macvlan/macvlan.go
- plugins/main/veth/veth.go
- scripts/docker-run.sh
- scripts/exec-plugins.sh
- scripts/priv-net-run.sh
ContainerID is now required so use that
or generate random bytes.
Fixes #5
> Do not use netns as ID or for entropy

- pkg/plugin/ipam.go
- pkg/plugin/types.go
- pkg/skel/skel.go
This reflects the latest SPEC draft.
> report errors via JSON

- plugins/ipam/dhcp/main.go
The dhcp daemon maybe running with a different cwd
and so the netns paths need to be absolute. This patch
also refactors the code to pull out the common, RPC
parts, out into a separate function.
> dhcp: make netns path absolute prior to RPC

- Documentation/bridge.md
- Documentation/dhcp.md
- Documentation/host-local.md
- Documentation/ipvlan.md
- Documentation/macvlan.md
Adds a .md file to the Documentation/ folder for each plugin.
> Document the plugins

- plugins/meta/flannel/flannel.go
Without it, packets leave via default route iface
and come back via interface added by flannel plugin.
If rp_filter=1, the packets are dropped.
> flannel: set up route for the entire flannel network

- pkg/ip/link.go
- plugins/main/ptp/ptp.go
> Fix veth setup

- SPEC.md
This adds an ability for networks to communicate
about the DNS nameservers they know about to the
container runtime.
Fixes #67
> spec: add "dns" field to the result JSON

- plugins/ipam/host-local/allocator.go
Fixes https://github.com/coreos/rkt/issues/1707
> host-local: detect missing subnet and error out

- SPEC.md
Version all artifacts using semantic versioning
so that plugins and container runtimes coded against
different versions of the spec can interoperate.
> spec: add cniVersion to results and config

- Documentation/ptp.md
- SPEC.md
- pkg/types/types.go
- plugins/main/bridge/bridge.go
- plugins/main/ipvlan/ipvlan.go
- plugins/main/macvlan/macvlan.go
- plugins/main/ptp/ptp.go
/cc @alban 
@thockin might be interested and helpful too
Fixes #100.
> *: DNS information as dictionary, adding domain, search domains and options

- plugins/ipam/host-local/config.go
Signed-off-by: André Martins <aanm90@gmail.com>
> fixed ipam host-local IP json tag

- pkg/types/types.go
Signed-off-by: André Martins <aanm90@gmail.com>
> added the String method to Result type

- plugins/main/loopback/loopback.go
- plugins/main/loopback/loopback_test.go
> Fix loopback result

- .travis.yml
- README.md
- test
> travis & README: add coveralls coverage report

- .travis.yml
> Use Ubuntu Trusty in travis

- plugins/ipam/host-local/allocator.go
> Fix govet warnings

- Godeps/Godeps.json
- vendor/github.com/coreos/go-iptables/iptables/iptables.go
> vendoring: bump coreos/go-iptables to 0.1.0

- pkg/ip/ipmasq.go
- pkg/utils/utils.go
- pkg/utils/utils_suite_test.go
- pkg/utils/utils_test.go
- plugins/main/bridge/bridge.go
- plugins/main/ptp/ptp.go
- test
> attempt to ensure chain name is unique and at most 29 chars long

- README.md
Changes:
4c778a6 (Brandon Philips, 51 seconds ago)
README: add some material on what CNI isn't
We get some questions about this stuff from time to time and I want to
acknowledge we have thought about them but aren't currently tackling them.
d5a8ec9 (Brandon Philips, 79 seconds ago)
README: add some more details on what CNI is
We needed a bit more intro material to scope what CNI does. Here is my
attempt.
> README: add some more introductory material

- pkg/testhelpers/testhelpers.go
Docs to accompany https://github.com/appc/cni/pull/181
> Document use of goroutine and LockOSThread in test helpers

- .travis.yml
- scripts/release-with-rkt.sh
This script uses rkt and a fedora image to build release tarballs.
> scripts: add "release with rkt"

- CONTRIBUTING.md
> Remove reference to policy on accepting PRs

- plugins/main/bridge/bridge.go
- plugins/main/ptp/ptp.go
> v0.2.x: cherry-pick masquerading clean-up fixes

- pkg/ns/consts_linux_386.go
- pkg/ns/consts_linux_amd64.go
- pkg/ns/consts_linux_arm.go
- pkg/ns/ns.go
See [\<kernel\>/arch/arm/include/uapi/asm/unistd.h](http://lxr.free-electrons.com/source/arch/arm/include/uapi/asm/unistd.h?v=4.4#L404)
> Correct setns syscall number on arm

- build
- test
> build: don't be verbose / test: fix bash variable escaping in sudo command 

- pkg/ns/ns.go
- pkg/ns/ns_test.go
> pkg/ns: don't allow operations after Close()

- pkg/ns/ns.go
- pkg/ns/ns_test.go
> pkg/ns: introduce error types indicate NS verification

- README.md
Mesos recently added support for CNI. The documentation can be found here:
https://github.com/apache/mesos/blob/master/docs/cni.md
> Added Mesos to CNI users.

- MAINTAINERS
Thank you Zach for all the great work done on CNI, farewell!
At the same time we are happy to welcome Dan amongst us who has already
contributed lots of valuable work!
> MAINTAINERS: remove @zachgersh, add @dcbw

- pkg/types/args_test.go
> pkg/types: unmarshal string tests

- SPEC.md
Based on previous discussions on the CNI maintainers calls, the spec is
unclear on 1) when CNI_ARGS should be used and 2) the fact the dynamic
config can be passed in through the network JSON.
This PR makes it clear that per-container config can be passed in
through the network JSON, adding a top level `args` field into
which orchestrators can add additional metadata without worrying that
plugins might reject the additional data. It also allows for plugins to
reject unknown fields passed in at the top level.
Using JSON is preferable to CNI_ARGS since it allows namespaced and
structured data. CNI_ARGS is a flat list of KV pairs which has reserved
characters with no escaping rules defined.
CNI_ARGS may still be used by orchestrators that want the simplicity of
passing the network config …
> SPEC: introduce "args" field and new error code

- .gitignore
- CONTRIBUTING.md
- Vagrantfile
Document a workflow that contributors can follow to get repeatable runs of the automated test suite inside a virtual machine.
I hope this makes it easier for new contributors to get involved.
Cheers.
> Add Vagrantfile, document how to run test suite in a vagrant VM

- plugins/ipam/host-local/allocator_test.go
ipam/host-local/allocator tests:
* cover requested IP
* improve error handling
> ipam/host-local/allocator tests: cover requested IP

- pkg/invoke/exec.go
- pkg/invoke/exec_test.go
- pkg/invoke/invoke_suite_test.go
- plugins/test/noop/debug/debug.go
- plugins/test/noop/main.go
Just adding tests, and introducing a bit of dependency injection.  Should make future refactors a little easier.
> Backfill tests for plugin execution

- plugins/ipam/host-local/allocator.go
- plugins/ipam/host-local/allocator_test.go
ref: https://github.com/kubernetes/kubernetes/issues/32844
> host-local: fix allocation of last address in a /30

- README.md
Added link to Infoblox IPAM plugin in README.
> Add link to Infoblox IPAM plugin

- pkg/ns/README.md
Re https://github.com/containernetworking/cni/issues/262#issuecomment-261224809
> Expand description of goroutine+netns problems

- libcni/conf.go
- libcni/conf_test.go
Content of the files are json, the configuration load should support .json
> libcni conf: support .json file extension

- libcni/api.go
- pkg/invoke/args.go
- pkg/ns/ns.go
- pkg/version/plugin.go
- plugins/ipam/host-local/backend/disk/backend.go
- plugins/ipam/host-local/backend/testing/fake_store.go
@containernetworking/cni-maintainers @squeed @rosenhouse @steveeJ
> all: assert internal objects implement interfaces

- SPEC.md
> spec: notice of version

- pkg/skel/skel.go
Enables plugins to perform custom error-handling.
Fixes #354
> skel: adds PluginMainWithError which returns a *types.Error

- SPEC.md
> Fix grammar

- SPEC.md
> spec: Remove `routes` from Network Configuration

- MAINTAINERS
> Add Bryan Boreham as maintainer

- pkg/testutils/cmd.go
- pkg/types/current/types_suite_test.go
- pkg/types/current/types_test.go
Fix an issue where Ginkgo can't print detailed failure info to stdout, and some pkg/types cleanups.
> tests: misc test fixes

- Documentation/spec-upgrades.md
@containernetworking/cni-maintainers An action-item from last week's meeting.
Big thanks for @dcbw for hammering out a great 1st draft.  I've re-worked it, but left both commits, so feel free to compare / revert my changes :-)
I've set "Allow edits from maintainers" so feel free to pile on more changes.  We can squash at merge-time.
> Documentation: guidance for upgrading to CNI Spec v0.3.0

- pkg/ip/link.go
- pkg/ip/link_test.go
- plugins/ipam/host-local/host_local_test.go
- plugins/main/bridge/bridge.go
- plugins/main/bridge/bridge_test.go
- plugins/main/ipvlan/ipvlan.go
- plugins/main/ipvlan/ipvlan_test.go
- plugins/main/macvlan/macvlan.go
- plugins/main/macvlan/macvlan_test.go
- plugins/main/ptp/ptp.go
- plugins/main/ptp/ptp_test.go
I wasn't able to test or updat the dhcp plugin. All the others are
tested and fixed
> plugins/*: Don't error if the device doesn't exist

- .travis.yml
- scripts/release-with-rkt.sh
This will help potentially to use cni releases directly in Kubernetes.
> Enable s390x build

- Documentation/cnitool.md
- libcni/conf.go
- libcni/conf_test.go
Also fixed some error reporting in the `cnitool`.
> Added documentation for `cnitool`

- SPEC.md
I was reading through the spec and noticed that it was labeled as a proposal. Is that the case?
Since we are already a few versions in, this feels more like a "specification" to me at this point. Somebody let me know if this was done intentionally - I am just here learning 😄
> Wondering if this is still a proposal?

- scripts/release-with-rkt.sh
- Use a new Fedora to get a more up to date Go version
- Don't build so many archives, they are not used.
- Handle the new build.sh script
- Just use host networking with rkt
> scripts/release-with-rkt.sh Minor improvements

- ROADMAP.md
> roadmap: add 1.0 items and clean things up

- GOVERNANCE.md
> docs: add Governance procedure documentation

- GOVERNANCE.md
> governance: add notes about public voting

- .appveyor.yml
- libcni/api_test.go
- libcni/backwards_compatibility_test.go
- libcni/libcni_suite_test.go
- pkg/invoke/get_version_integration_test.go
- pkg/version/legacy_examples/examples.go
- pkg/version/legacy_examples/legacy_examples_test.go
- pkg/version/testhelpers/testhelpers_test.go
- plugins/test/noop/noop_test.go
Adding AppVeyor
[Build output here](https://ci.appveyor.com/project/rosenhouse/cni)
Next steps (after this is merged):
- enable the AppVeyor integration on GitHub
- add the badge to the README
> Add CI for Windows

- CONVENTIONS.md
Also, restructure the document slightly.
This convention is implemented in containernetworking/plugins#95
> CONVENTIONS: add new `ipRanges` capability.

- README.md
> README: add ovn-kubernetes to the plugin list

- SPEC.md
- libcni/api.go
- plugins/test/noop/noop_test.go
This is to fix up #551 against the latest code updates.
> Network interface name matters, updated

- libcni/api.go
I happened to find it by refreshing my plugin PR, https://travis-ci.org/containernetworking/plugins/jobs/394863200.
> Fix broken build for cni introduced by https://github.com/containernetworking/cni/pull/524

- SPEC.md
Fixes: #564
@containernetworking/cni-maintainers @bboreham
> spec: be explicit about optional and required structure members

- pkg/skel/skel.go
- pkg/skel/skel_test.go
Instead of:
```
CNI_COMMAND env variable missing
<about message here>
{
"code": 100,
"msg": "required env variables missing"
}
```
print:
`<about message here>`
@squeed @bboreham @jellonek @containernetworking/cni-maintainers
> skel: only print about message, not errors

- .gitignore
- Documentation/spec-upgrades.md
- cnitool/cnitool.go
- libcni/api.go
- libcni/api_test.go
- libcni/backwards_compatibility_test.go
- libcni/libcni_suite_test.go
- pkg/invoke/delegate.go
- pkg/invoke/delegate_test.go
- pkg/invoke/exec.go
- pkg/invoke/exec_test.go
- pkg/invoke/fakes/raw_exec.go
- pkg/invoke/get_version_integration_test.go
- pkg/invoke/raw_exec.go
- pkg/invoke/raw_exec_test.go
- plugins/test/sleep/main.go
#567
To fix this problem.
No timeout when cni call cni binary file.
> No timeout when cni call cni binary file.

- README.md
DANM -a K8s networking solution using CNI- was recently made opensource.
PR expands the list of 3rd party plugins with the reference to the project.
> README: expands list of 3rd party plugins with DANM

- README.md
Adding a link to documentation with instructions for how to install the VMware NSX CNI plugin.
> Added VMware NSX CNI plugin to CNI plugin list.

- CONTRIBUTING.md
- pkg/version/legacy_examples/example_runtime.go
Signed-off-by: Nguyen Phuong An <AnNP@vn.fujitsu.com>
> Remove duplicate word 'the the'.

- CONTRIBUTING.md
- README.md
- SPEC.md
Signed-off-by: Nguyen Van Trung <trungnv@vn.fujitsu.com>
> Change http to https for security links

- CONVENTIONS.md
Ref: https://github.com/containernetworking/cni/pull/648
> Fix 404 not found

- Documentation/spec-upgrades.md
Make it point to a specific web page
> update spec-upgrades.md make it point to a specific web page

- SPEC.md
Fix spell error for configuration json.
Add missing comma.
> Fix spell error for configuration json

- CONTRIBUTING.md
- pkg/version/legacy_examples/example_runtime.go
Fix some spell errors, double words.
> Fix some spell errors

- cnitool/README.md
> Upgrade to cni spec v0.4.0.

- libcni/api.go
Add GetNetworkListCachedResult method to CNI interface
> Add GetNetworkListCachedResult method to CNI interface

- .travis.yml
- Vagrantfile
- scripts/release.sh
> Release: bump go to v1.12

- pkg/skel/skel.go
Sorry for forgetting to remove needless functions and types in #686 , this PR try to follow up.
> skel: remove needless functions and types

- Documentation/cnitool.md
- cnitool/README.md
Just some markdown cleanup and I added the used environment variables directly to the cnitool `README.md` and added a reference from the Documentation file.
> Update cnitool docs

- .travis.yml
Refs: 
* https://github.com/containernetworking/plugins/pull/386
* https://golang.org/doc/go1.13
Signed-off-by: Tomasz Janiszewski <janiszt@gmail.com>
> Bump golang

- pkg/invoke/args.go
Signed-off-by: yuxiaobo <yuxiaobogo@163.com>
> Perfect annotation: Correct word spelling mistakes

- README.md
> Add a note to README about where to find the binaries

- README.md
> Update README to sunset slack and call out kubecon presentations

- README.md
> Add security reporting info

- pkg/types/internal/convert.go
Signed-off-by: Hu Shuai <hus.fnst@cn.fujitsu.com>
> Fix typo in pkg/types/internal/convert.go

- CONVENTIONS.md
Add "alias" to conventions
Signed-off-by: Michael Cambria <mcambria@redhat.com>
> Add "alias" to conventions

- pkg/invoke/find.go
- pkg/invoke/find_test.go
> tighten up plugin-finding logic

- README.md
Adding reference to Azure CNI in the README.
> Adding reference to Azure CNI as 3rd party plugin in README

- SPEC.md
The protocol is unchanged, but the specification was badly in need of a rewrite.
> Rewrite spec.md for 1.0.0

- SPEC.md
> typos correct

- SPEC.md
Found some minor improvements during reading.
Corrected some typos, added a working link and some formatting corrections.
Added detail regarding used CNI_IFNAME in examples which might help others for better understanding.
> spec: Some minor corrections

- CONVENTIONS.md
A documentation improvement after [https://github.com/containernetworking/plugins/pull/630](https://github.com/containernetworking/plugins/pull/630) merged.
> chore: standardize documentation on IP assignment

- SPEC.md
> spec: bump to 1.0.0

- scripts/exec-plugins.sh
add ability to run configurations with plugin lists/chaning
see SPEC >= 0.3.1
> [exec-plugins]: support plugin lists

- README.md
[hybridnet link](https://github.com/alibaba/hybridnet)
Since the old pr #869 has sunk, open another one to refresh this.
> introduce hybridnet to thrid-party plugins

- MAINTAINERS
> cdc: update email

- README.md
Signed-off-by: loxi-admin <admin@netlox.io>
> Removed loxilight as it is not supported anymore

- pkg/utils/utils.go
Signed-off-by: yanggang <gang.yang@daocloud.io>
Like commit diffs , fix the typo notes.
> fix wrong notes for ValidateInterfaceName()

- .golangci.yml
- libcni/conf.go
- pkg/skel/skel.go
Signed-off-by: Matthieu MOREL <matthieu.morel35@gmail.com>
> ci(lint): enable errorlint linter

- libcni/api.go
- libcni/api_test.go
Port over `getCachedNetworkInfo` routine from cri-o/ocicni to CNI library.
`getCachedNetworkInfo` routine is currently implemented in [cri-o/ocicni](https://github.com/cri-o/ocicni/blob/master/pkg/ocicni/ocicni.go#L576-L642).
I think it would be useful to have this routine in CNI library and shared with other consumers. One use case is the network GC feature that I am working on for containerd, this routine can be used to provide a list of all network attachments known to CNI during GC.
> Porting over getCachedNetworkInfo routine from cri-o

- SPEC.md
- pkg/types/types.go
- pkg/types/types_test.go
> Add Scope property for routes

- SPEC.md
> spec: remove "-dev" tag

- .github/workflows/commands.yml
- .github/workflows/scorecard.yml
- .github/workflows/test.yaml
- .yamllint.yaml
- README.md
> Setup scorecard workflow

- README.md
This includes a link to a calendar event.
> moving meeting to bi-weekly
