containernetworking/cni

plugins/main/ipvlan/ipvlan.go
Add the ipvlan main plugin which is heavily based on the macvlan plugin.
Availabile modes for this plugin are l2 and l3, wheres l2 has the higher
compatibility due to support for multicast and broadcasts. L2 has therefore been
chosen as the default mode.
See the official docs at
https://www.kernel.org/doc/Documentation/networking/ipvlan.txt
for more information.
Fixes #6.
=> plugins: add ipvlan main plugin

pkg/plugin/ipam.go, pkg/plugin/types.go, pkg/skel/skel.go, plugins/ipam/dhcp/main.go, plugins/ipam/host-local/main.go, plugins/main/bridge/bridge.go, plugins/main/ipvlan/ipvlan.go, plugins/main/macvlan/macvlan.go, plugins/main/veth/veth.go, scripts/exec-plugins.sh
When plugin errors out, it prints out a JSON object to stdout
describing the failure. This object needs to be propagated out
through the plugins and to the container runtime. This change
also adds Print method to both the result and error structs
for easy serialization to stdout.
=> Propagate json error object to the caller

Documentation/flannel.md, README.md, build, plugins/meta/flannel/flannel.go
This introduces a notion of a "meta" plugin. A meta plugin
is one that delegates the actual work of setting up the interface
to the main plugin. The meta plugin is used to select and dynamically
configure the main plugin. The sequence of events, is as follows:
Given netconf like:
```
{
"name": "mynet",
"type": "flannel",
"delegate": {
"type": "bridge"
}
}
```
flannel fills in values like "mtu", "ipam.subnet" and delegates to
"bridge" main plugin. "bridge" plugin will operate as usual, calling
into ipam module for IP assignment.
Delegate dictionary should not contain "name" field as it will be
filled in by the flannel plugin.
=> add flannel plugin

Godeps/_workspace/src/github.com/d2g/dhcp4client/client.go, Godeps/_workspace/src/github.com/d2g/dhcp4client/pktsock_linux.go, Godeps/_workspace/src/github.com/vishvananda/netlink/addr_linux.go, Godeps/_workspace/src/github.com/vishvananda/netlink/link_linux.go, Godeps/_workspace/src/github.com/vishvananda/netlink/neigh_linux.go, Godeps/_workspace/src/github.com/vishvananda/netlink/netlink.go, Godeps/_workspace/src/github.com/vishvananda/netlink/protinfo_linux.go, Godeps/_workspace/src/github.com/vishvananda/netlink/route_linux.go, Godeps/_workspace/src/github.com/vishvananda/netlink/xfrm_policy_linux.go, Godeps/_workspace/src/github.com/vishvananda/netlink/xfrm_state_linux.go, Godeps/_workspace/src/golang.org/x/sys/unix/creds_test.go, Godeps/_workspace/src/golang.org/x/sys/unix/mmap_unix_test.go, Godeps/_workspace/src/golang.org/x/sys/unix/syscall_bsd_test.go, Godeps/_workspace/src/golang.org/x/sys/unix/syscall_test.go, Godeps/_workspace/src/golang.org/x/sys/unix/syscall_unix_test.go, build, pkg/ip/ipmasq.go, pkg/ip/link.go, pkg/ip/route.go, pkg/plugin/ipam.go, plugins/ipam/dhcp/daemon.go, plugins/ipam/dhcp/lease.go, plugins/ipam/dhcp/options.go, plugins/ipam/dhcp/options_test.go, plugins/main/bridge/bridge.go, plugins/main/ipvlan/ipvlan.go, plugins/main/macvlan/macvlan.go, plugins/main/veth/veth.go
Path rewriting causes too many problems when vendoring
vendored code. When CNI code is vendored into rkt,
godep has problems code already vendored by CNI.
=> No more path rewriting

plugins/main/ipvlan/ipvlan.go
Instead of temp (random) name, the final name (e.g. eth0)
was used during link creation. This would collide on hosts
that already had the an interface with such a name.
=> ipvlan: wrong name was used during link creation

Documentation/host-local.md, pkg/plugin/args.go, plugins/ipam/host-local/allocator.go, plugins/ipam/host-local/config.go, plugins/ipam/host-local/main.go
A specific IP can now be requested via the environment variable CNI_ARGS, e.g.
`CNI_ARGS=ip=1.2.3.4`.
The plugin will try to reserve the specified ip.
If this is not successful the execution will fail.
Working on #39.
=> host-local: allow ip request via CNI_ARGS

pkg/plugin/ipam.go
Make it more clear that we failed to find an IPAM plugin.
Check for a missing plugin name and issue a more helpful error.
Fixes #52
=> IPAM plugin: improve error messages

plugins/main/ipvlan/ipvlan.go, plugins/main/macvlan/macvlan.go
Luckily the docs haven't mentioned support for ipMasq for both plugins so far.
Even if anyone has attempted to enable the feature in their configuration files it didn't have the desired effect for the network.
Closes #14.
=> ipvlan/macvlan: remove ipMasq related code

libcni/api.go, pkg/invoke/exec.go, pkg/ipam/ipam.go
When plugin is executed with a DEL command, it does not
print result to stdout unless there is an error. Therefore
it stdout bytes should not be passed to json.Unmarshal.
=> bug fix: exec of DEL cmd caused JSON decode error

plugins/main/ptp/ptp.go
In some cases the route deletion would fail due to wrong
scope. It should be NOWHERE when deleting (per iproute2).
This also adds more verbose error messages.
=> Route del would fail due to wrong scope; better errors

Documentation/flannel.md, plugins/meta/flannel/flannel.go
- Document that flannel outputs FLANNEL_NETWORK b/c we use it
- Check and error out if expecited fields are missing in subnetEnv file
Fixes #72
=> flannel: doc fix and check for missing subnet.env fields

plugins/ipam/dhcp/lease.go
With this we still get the "network is down" error, but after the 2nd
retry the interface is up and the dhcp request works.
Fixes #81.
=> dhcp: detect if link is down and attempt to set up

SPEC.md
Removes the "addIf" attribute from the example of a bridge network
definition. This doesn't appear to exist in the implementation.
=> spec: Removed reference to unsupported addIf attribute

Documentation/ptp.md, pkg/types/types.go, plugins/main/bridge/bridge.go, plugins/main/ipvlan/ipvlan.go, plugins/main/macvlan/macvlan.go, plugins/main/ptp/ptp.go
appc/cni#76 added a "dns" field in the result JSON. But before this
patch, the plugins had no way of knowing which name server to return.
There could be two ways of knowing which name server to return:
1. add it as an extra argument ("CNI_ARGS")
2. add it in the network configuration as a convenience (received via
stdin)
I chose the second way because it is easier. In the case of rkt, it
means the user could just add the DNS name servers in
/etc/rkt/net.d/mynetwork.conf.
=> *: add "dns" field to the configuration

Godeps/Godeps.json, Godeps/_workspace/src/github.com/coreos/go-iptables/iptables/iptables.go, Godeps/_workspace/src/github.com/coreos/go-iptables/iptables/iptables_test.go, Godeps/_workspace/src/github.com/coreos/go-iptables/iptables/lock.go
We need the wait behavior, otherwise we get:
Jan 27 19:40:39 kubernetes-node-1 kubelet[4897]: E0127 19:40:39.465904    4897 manager.go:1885] Failed to setup network for pod "heapster-v11-dgahz_kube-system(a55f02dc-c52c-11e5-803e-525400ebdc4d)" using network plugins "kubenet": Error adding container to network: exit status 4: Another app is currently holding the xtables lock. Perhaps you want to use the -w option?
=> Revendor go-iptables to get --wait behavior

MAINTAINERS
Eugene is no longer with CoreOS or actively involved with CNI, so remove
him from the current list of maintainers. He'll be gladly welcomed back
if he decides to rejoin the project.
=> MAINTAINERS: remove Eugene from list

Documentation/tuning.md, plugins/meta/tuning/tuning.go, test
Allow users to tune net network parameters such as somaxconn.
With this patch, users can add a new network configuration:
```
> {
>   "name": "mytuning",
>   "type": "tuning",
>   "sysctl": {
>           "net.core.somaxconn": "500"
>   }
> }
```
The value /proc/sys/net/core/somaxconn will be set to 500 in the network
namespace but will remain unchanged on the host.
Only sysctl parameters that belong to the network subsystem can be
modified.
Related to: https://github.com/coreos/rkt/pull/2140
=> new plugin: tuning

.travis.yml
- Build against more versions of Go
- Explicitly specify go versions
- Remove the notifications line (it wasn't doing anything)
=> Tweak the travis file

libcni/api.go, pkg/invoke/exec.go, pkg/invoke/find.go, pkg/invoke/find_test.go, pkg/invoke/invoke_suite_test.go, pkg/ipam/ipam.go
Depends on #121 
---
Previously when the plugin failed to be found the error message would be unhelpful:
```
mynet : error executing ADD: could not find "." plugin
```
Now, error message looks like
```
mynet : error executing ADD: failed to find plugin "some-plugin" in path [/gopath/src/github.com/appc/cni/bin]
```
-  Added tests in the ginkgo style (which means ginkgo / gomega are godep'ed)
- Tests are now run as part of the testing script
- Testing style of `/pkg/invoke` is now much more descriptive + covers edge cases
- ginkgo / gomega style tests still work with the regular old `go test` command
=> Better error messages when plugin is not found

README.md, test
Now that the ginkgo / gomega dependencies have been merged - the tests for find can be turned on.
I have also added a travis badge to show that the build is passing!
=> More tests

pkg/invoke/delegate.go, pkg/ipam/ipam.go, plugins/meta/flannel/flannel.go
The 'flannel' meta plugin delegates to other plugins to do the actual
OS-level work. It used the ipam.Exec{Add,Del} procedures for this
delegation, since those do precisely what's needed.
However this is a bit misleading, since the flannel plugin _isn't_
doing this for IPAM, and the ipam.Exec* procedures aren't doing
something specific to IPAM plugins.
So: anticipating that there may be more meta plugins that want to
delegate in the same way, this commit moves generic delegation
procedures to `pkg/invoke`, and makes the `pkg/ipam` procedures (still
used, accurately, in the non-meta plugins) shims.
See issue #123.
=> Add invoke.Delegate{Add,Del} for use by meta-plugins

MAINTAINERS
We are pleased to welcome Zach on board as CNI maintainer.
Happy collaboration!
=> MAINTAINERS: welcome Zach!

pkg/ns/ns.go, pkg/ns/ns_suite_test.go, pkg/ns/ns_test.go, test
Without this, an error in the callback function would leave the caller of WithNetNS in the wrong namespace.
=> WithNetNS restores original namespace when callback errors

pkg/skel/skel_suite_test.go, pkg/skel/skel_test.go, test
This is an attempt to testing the PluginMain() function of the skel pkg.
We should be able to do better by using a mockable interface for the
plugins, but this is a start.
=> pkg/skel: add rudimentary unit tests

build
Missed this when finishing out #156
=> build script: remove the _workspace from GOPATH

build
go-1.6 enables vendor by default, but go-1.5 needs an environment variable.
=> scripts: fix build with go-1.5 after switch to vendor/

.travis.yml
The problem:
```
$ go get golang.org/x/tools/cmd/vet
package golang.org/x/tools/cmd/vet: cannot find package "golang.org/x/tools/cmd/vet" in any of:
/nix/store/4g8l1pw42rnai7m989q61dm65rg2bcqm-go-1.6/share/go/src/golang.org/x/tools/cmd/vet (from $GOROOT)
/home/steveej/.gopath_1.6_generic/src/golang.org/x/tools/cmd/vet (from $GOPATH)
```
=> travis: don't go get vet

.travis.yml, pkg/utils/sysctl/sysctl_linux.go, plugins/main/macvlan/macvlan.go
=> Macvlan arp proxy

pkg/ns/ns_test.go, pkg/testhelpers/testhelpers.go, pkg/testhelpers/testhelpers_suite_test.go, pkg/testhelpers/testhelpers_test.go, plugins/main/loopback/loopback_suite_test.go, plugins/main/loopback/loopback_test.go, test
As we backfill tests, it is useful to extract a common package of test helpers.
This PR pulls some basic test harness code out of `loopback` and `ns` package test suites and makes them available for other tests.
Because the test helpers contain some non-trivial code (syscalls for `unshare`, `mount`, etc), I've backfilled unit tests of the test helpers themselves.  Those backfilled tests exposed a couple bugs in `MakeNetworkNS`, which I've fixed in the final commit.
You can see the test failures in Travis on the second-to-last commit, and then the fix on the final commit.
Happy to squash those last two if you prefer.
=> Extract and improve test helpers

pkg/ns/ns_test.go, pkg/testhelpers/testhelpers.go
/proc/self/ns/net gives the main thread's namespace, not necessarily
the namespace of the thread that's running the testcases.  This causes
sporadic failures of the tests.  For example, with a testcase reading
inodes after switching netns:
/proc/27686/task/27689/ns/net 4026532565
/proc/self/ns/net 4026531969
/proc/27686/task/27689/ns/net 4026532565
See also:
https://github.com/vishvananda/netns/commit/008d17ae001344769b031375bdb38a86219154c6
```
Running Suite: pkg/ns Suite
===========================
Random Seed: 1459953577
Will run 6 of 6 specs
• Failure [0.028 seconds]
Linux namespace operations
/cni/gopath/src/github.com/appc/cni/pkg/ns/ns_test.go:167
WithNetNS
/cni/gopath/src/github.com/appc/cni/pkg/ns/ns_test.go:166
executes the callback within the target network namespace [It] …
```
=> ns: fix reading net namespace in multi-threaded processes

README.md
The word "standard" does not represent what CNI is actually trying to
be.
=> README: clarify what CNI is

plugins/main/bridge/bridge.go
In the Add command we set up masquerading rules that didn't have a
corresponding clean-up code in Del.
Add the clean-up code.
=> plugins/bridge: clean masquerading rules

plugins/main/bridge/bridge.go, plugins/main/ptp/ptp.go
This will allow the IPAM allocations to be cleared in case the
interfaces and iptables rules are non-existent.
Fixes #204 
/cc @iaguis @tomdee
=> plugins/{ptp,bridge}: teardown first

plugins/main/bridge/bridge.go
In the Add command we set up masquerading rules that didn't have a
corresponding clean-up code in Del.
Add the clean-up code.
Blocked by
=> v0.2.X cherry-pick masquerading rules cleanup

plugins/main/macvlan/macvlan.go
The macvlan is initially created in a separate network namespace
and the sysctl must be set in that namespace too.
Fixes #208.
=> macvlan: sysctl must be set in macvlan interface's namespace

README.md
Simplify and use plainer language in the description of CNI.
=> Simplify README preamble

CONTRIBUTING.md
=> docs: Mention license headers and doc contributions

plugins/main/bridge/bridge.go
Not using NewLinkAttrs() or not initializing TxQLen leaves
the value as 0, which tells the kernel to set a zero-length
tx_queue_len.  That messes up FIFO traffic shapers (like pfifo)
that use the device TX queue length as the default packet
limit.  This leads to a default packet limit of 0, which drops
all packets.
=> bridge: leave TX queue length as kernel default, not 0

Documentation/bridge.md, plugins/main/bridge/bridge.go, plugins/main/bridge/bridge_test.go
When isDefaultGateway is true it automatically sets isGateway to true.
The default route will be added via the (bridge's) gateway IP.
If a default gateway has been configured via IPAM in the same configuration file, the plugin will error out.
Fixes #27.
Fixes #184.
=> bridge: add isDefaultGateway field

pkg/ns/ns.go, pkg/ns/ns_test.go
=> pkg/ns: verify netns when initialized with GetNS

pkg/ns/ns.go, pkg/ns/ns_test.go
=> pkg/ns: consider PROCFS during NS verification

pkg/skel/skel.go, pkg/skel/skel_test.go, plugins/main/bridge/bridge.go, plugins/main/ipvlan/ipvlan.go, plugins/main/macvlan/macvlan.go, plugins/main/ptp/ptp.go
This will allow to free up the IPAM allocations when the caller doesn't
have access to the network namespace anymore, e.g. due to a reboot.
Fixes #220.
=> plugins: don't require CNI_NETNS for DEL command

ROADMAP.md
Contributes to #125.
/cc @squaremo
=> Add ROADMAP document

plugins/ipam/host-local/allocator.go, plugins/ipam/host-local/allocator_test.go, plugins/ipam/host-local/backend/disk/backend.go, plugins/ipam/host-local/backend/store.go, plugins/ipam/host-local/backend/testing/fake_store.go, plugins/ipam/host-local/config.go, plugins/ipam/host-local/host_local_suite_test.go, test
plugins: round robin ip allocation for host-local ipam
host-local ipam search for available ips from start of subnet. Hence it tends to allocate ip that are used recently. This is not ideal since it may cause collisions. This PR changes the ip allocation logic to round robin.  
fixes #194
related PR: #196
=> round robin ip allocation for host-local ipam

.travis.yml
* cleanup structure
* explicitly use go-{1.5.4,1.6.2}
=> travis: cleanup and bump go versions

pkg/types/args.go
Allow strings to be unmarshalled for CNI_ARGS
CNI_ARGS uses types.LoadArgs to populate a struct.
The fields in the struct must meet the TextUnmarshaler interface.
This code adds a UnmarshallableString type to assist with this.
=> pkg/types: Add UnmarshallableString type

README.md
README: grammatical corrections - two commas and a hyphen
To improve legibility and understanding, I added two commas and a hyphen as grammatical corrections to the README.md
=> README: grammatical corrections

plugins/main/ptp/ptp_suite_test.go, plugins/main/ptp/ptp_test.go, test
=> plugins/main/ptp: add functional tests

pkg/skel/skel.go, pkg/skel/skel_test.go, pkg/testutils/bad_reader.go
A refactor that provides better unit test coverage and modularity for the `skel.PluginMain` behavior.
Should make it easier to add features in the future, e.g. #267 
And coverage on `pkg/skel` jumped from 50% to 80% !
Cheers.
=> Refactor skel with dependency injection

build, libcni/api_test.go, libcni/conf_test.go, libcni/libcni_suite_test.go, pkg/testutils/bad_reader.go, plugins/test/noop/debug/debug.go, plugins/test/noop/main.go, plugins/test/noop/noop_suite_test.go, plugins/test/noop/noop_test.go, test
The `libcni` package provides the public API used by container runtimes, including loading configuration files from disk and executing plugins.
It is currently untested.  This PR adds integration tests, primarily to catch any regressions that might arise as we add new functionality (e.g. #267).
The tests of the plugin execution use a new "no-op" plugin.  The no-op plugin does not touch namespaces or the network stack.  Instead it records its inputs and can be configured to respond with arbitrary data or to error.  The tests use it to verify behavior of the plugin execution code.
=> Add integration tests of libcni

README.md
Following up on a suggestion I made in https://github.com/containernetworking/cni/pull/259#issuecomment-234377787 I've expanded the README's list of CNI users to explicitly call out 3rd party plugins.
The idea being that we can encourage plugin authors to publish their code in their own source code repository and then we can link to it.  This reduces the maintenance burden on us, but still provides a informal index for the plugin ecosystem.
=> README: distinguish between runtimes and plugins

pkg/ip/link.go, pkg/ip/link_test.go
If interface name for a container provided by a user is already present,
Veth creation fails with incorrect error.
If os.IsExist error is returned by makeVethPair:
* Check for peer name, if exists generate another random peer name, 
* else, IsExist error is due to container interface present, return error.
Fixes #155
=> pkg/ip: Return correct error if container name provided exists, and test cases

Documentation/bridge.md, libcni/conf.go, libcni/conf_test.go, plugins/main/bridge/bridge.go, plugins/main/bridge/bridge_test.go
Instead of throwing error it is better reconfigure the bridge IP address.
Currently the CNI plugin is used in kubernetes and after hyperkube restart cni0 bridge retains its old value. This PR fix the issue.
=> Reconfigure bridge IP address

Documentation/tuning.md, SPEC.md, pkg/skel/skel.go, pkg/skel/skel_test.go, pkg/version/version.go
At last CNI meeting, I volunteered to put together a first draft of spec versioning support, see https://github.com/containernetworking/cni/issues/266
This small PR is the first step -- add a VERSION command to all plugins transparently -- plugin authors only need to re-compile.
The `VERSION` is bumped to `0.2.0` because this new command was added.  There are no incompatibilities with `0.1.0`
=> Adds VERSION command

pkg/ip/link.go, pkg/ip/link_test.go
The veth is moved from the container NS to the host NS.
This is handled by the code that sets the link to UP but the wrong
hostVeth is returned to the calling code.
=> pkg/ip: Ensure that SetupVeth returns correct hostVeth

pkg/ns/ns.go
The expectation on older kernels (< 3.19) was to have the network
namespace always be a directory. This is not true if the network
namespace is bind mounted to a file, and will make the plugin fail
erroneously in such cases.
I have tried this with Mesos on a CentOS 7 cluster, running 3.10 kernel and it works fine. Moreover, have also tried it on Ubuntu 14.04 which has 3.13 kernel and works fine on that as well. 
This should fix #288
=> Fixed the check for network namespace path.

plugins/ipam/host-local/allocator.go, plugins/ipam/host-local/allocator_test.go
This fixes a couple of issues with RangeEnd/RangeStart and also has a different take on https://github.com/containernetworking/cni/pull/292.
=> Fix handling of host-local IP address ranges

README.md, libcni/api_test.go, pkg/invoke/exec.go, pkg/invoke/exec_test.go, pkg/invoke/raw_exec_test.go, pkg/skel/skel.go, pkg/skel/skel_test.go, pkg/types/types.go, pkg/version/conf.go, pkg/version/conf_test.go, pkg/version/plugin.go, pkg/version/reconcile.go, pkg/version/reconcile_test.go, plugins/main/bridge/bridge_test.go, plugins/main/ipvlan/ipvlan_test.go, plugins/main/loopback/loopback_test.go, plugins/main/macvlan/macvlan_test.go, plugins/main/ptp/ptp_test.go, plugins/test/noop/noop_test.go
Another step in the [versioning effort](https://github.com/containernetworking/cni/issues/266).
Building on #287, this PR puts version checks into the `skel` package, before the `cmdAdd` and `cmdDel` callbacks.
This way, the callbacks will only get called if stdin data (a.k.a. ["network configuration"](https://github.com/containernetworking/cni/blob/master/SPEC.md#network-configuration) a.k.a. `NetConf`) contains a `cniVersion` field that matches one of the `supportedVersions` that the plugin self-declared.
Importantly, legacy config that is missing the `cniVersion` field is assumed to be version 0.1.0 (thanks @dcbw), and will continue to work even with newer plugins build with this version of the library.
=> Plugins validate cniVersion of NetConf

CONTRIBUTING.md, README.md
Motivated by https://github.com/containernetworking/cni/issues/300#issuecomment-251032278 and https://github.com/containernetworking/cni/pull/259#issuecomment-234377787
@containernetworking/cni-maintainers : thoughts?
=> 3rd party plugins belong in their own repos

.travis.yml, libcni/backwards_compatibility_test.go, pkg/version/legacy_examples/examples.go, pkg/version/legacy_examples/legacy_examples_suite_test.go, pkg/version/legacy_examples/legacy_examples_test.go
Before we change the structures in the `types` package (e.g.. #145), I propose that we add tests to ensure that newer versions of `libcni` will continue to be able to parse the output from older plugins.
Right now, this new test passes trivially.  It will become valuable once our `types` start changing.
@dcbw @containernetworking/cni-maintainers
=> A test verifies that libcni is backwards compatible with legacy plugins

pkg/skel/skel_test.go
Fixes an oversight in the tests of the `skel` package
=> skel tests: correct name of CNI_CONTAINERID in tests of env vars

libcni/api_test.go, libcni/backwards_compatibility_test.go, libcni/libcni_suite_test.go, pkg/version/legacy_examples/example_runtime.go
This test compiles a trivial client with a fixed version libcni. It then creates and destroys a ptp network using the most recent plugin.
It's basically a simplified version of `ptp_test.go` in a single file.
=> testing: test invocation of newer plugins with an older libcni

Godeps/Godeps.json, plugins/main/ipvlan/ipvlan.go, vendor/github.com/vishvananda/netlink/bpf_linux.go, vendor/github.com/vishvananda/netlink/filter.go, vendor/github.com/vishvananda/netlink/link.go, vendor/github.com/vishvananda/netlink/link_linux.go, vendor/github.com/vishvananda/netlink/neigh_linux.go, vendor/github.com/vishvananda/netlink/nl/link_linux.go, vendor/github.com/vishvananda/netlink/nl/nl_linux.go, vendor/github.com/vishvananda/netlink/route_linux.go, vendor/github.com/vishvananda/netlink/rule_linux.go
In kernel commit https://github.com/torvalds/linux/commit/4fbae7d83c98c30efcf0a2a2ac55fbb75ef5a1a5 "L3-symmetric' mode was added to IPVLAN.
This PR updates netlink to a revision that has the correct definition for this, and adds support for it to the IPVLAN plugin.
=> ipvlan: Support L3-Symmetric mode

plugins/test/noop/main.go, plugins/test/noop/noop_test.go
The `noop` CNI plugin can be useful when testing other CNI plugins (i.e. delegating to noop plugin).
The only problem I encountered was when **CNI_ARGS** had more than one key/value pair, the noop plugin fails to load the debug file. Basically it is expecting only a single CNI_ARG pair.
This PR is just an update to noop plugin to parse the **CNI_ARGS** pairs, to allow more than just
the `DEBUG` arg.
```sh
CNI_ARGS="DEBUG=/path/to/file;FOO=BAR;ABC=123"
```
Cheers
cc: @rosenhouse
=> noop plugin: support multiple CNI_ARGS

plugins/ipam/host-local/backend/disk/backend.go, plugins/ipam/host-local/config.go, plugins/ipam/host-local/host_local_test.go, plugins/ipam/host-local/main.go
Add an e2e host-local plugin testcase, which requires being able
to pass the datadir into the plugin so we can erase it later.
We're not always guaranteed to have access to the default data
dir location, plus it should probably be configurable anyway.
=> host-local: add DataDir IPAM conf option and use it for testcases

Documentation/flannel.md, plugins/meta/flannel/flannel.go, plugins/meta/flannel/flannel_suite_test.go, plugins/meta/flannel/flannel_test.go, test
We'd like to be able to configure where the flannel cni plugin stores its state. This is currently hard coded to `/var/lib/cni/flannel`. This PR adds an optional `stateDir` to the flannel NetConf, and if this is not present it defaults to `/var/lib/cni/flannel`.
=> Allow flannel CNI plugin stateDir to be configurable

plugins/ipam/host-local/README.md
The configuration example in host-local README.md used wrong syntax for rangeStart and rangeEnd.
=> Fix README.md host-local IPAM range start/end typo

plugins/ipam/host-local/backend/disk/backend.go, plugins/ipam/host-local/host_local_test.go
It doesn't seem like container IDs should really have whitespace or
newlines in them.  As a complete edge-case, manipulating the host-local
store's IP reservations with 'echo' puts a newline at the end, which
caused matching to fail in ReleaseByID().  Don't ask...
@containernetworking/cni-maintainers @squeed @steveeJ
=> host-local: trim whitespace from container IDs and disk file contents

plugins/test/noop/debug/debug.go, plugins/test/noop/main.go, plugins/test/noop/noop_test.go
This makes it a little bit easier to get started writing tests using the no-op plugin.
cc: @karampok
=> plugins/noop: return a helpful message for test authors

.travis.yml
- Start testing against Go 1.7.x
- No longer test against Go 1.5.x
According to the Go language [Release Policy](https://golang.org/doc/devel/release.html#policy):
> Each major Go release obsoletes and ends support for the previous one. 
> ...
> As a special case, we issue minor revisions for critical security problems in both the current release and the previous release. 
Therefore, Go 1.5.x hasn't been supported for security fixes since last August.
=> travis: roll forward the versions of Go that we test

plugins/ipam/host-local/backend/allocator/allocator.go, plugins/ipam/host-local/backend/allocator/allocator_suite_test.go, plugins/ipam/host-local/backend/allocator/allocator_test.go, plugins/ipam/host-local/backend/allocator/config.go, plugins/ipam/host-local/main.go, test
There's a lot of code that can be used by third parties in the IPAM host-local module (for example the configuration types).
Is it okay to split this up so it can be used by other packages?
Thanks!
Signed-off-by: André Martins aanm90@gmail.com
=> ipam/host-local: Move allocator and config to backend

Documentation/host-local.md, plugins/ipam/host-local/README.md, plugins/ipam/host-local/backend/allocator/config.go, plugins/ipam/host-local/dns.go, plugins/ipam/host-local/dns_test.go, plugins/ipam/host-local/host_local_test.go, plugins/ipam/host-local/main.go
This adds the option `resolvConf` to the host-local IPAM configuration. If specified, the plugin will try to parse the file as a resolv.conf(5) type file and return it in the DNS response.
=> ipam/host-local: add ResolvConf argument for DNS configuration

SPEC.md, libcni/api.go, libcni/api_test.go, libcni/conf.go, libcni/conf_test.go, pkg/types/types.go, plugins/test/noop/main.go, plugins/test/noop/noop_test.go
Implements @squeed "ordered" suggestion in https://gist.github.com/squeed/c69206c51f7d38d1cbb5211a3fde5d06.
Shows how both IPAM and regular plugins need to be modified to support prevResult and missing IPAM structures (since IPAM could also be in a standalone config block).
One missing piece is versioning of course, which needs to be bumped for this. I don't think we yet need to do everything #145 does since this doesn't change structures in a backwards compatible way.
@containernetworking/cni-maintainers @rosenhouse @squeed @freehan @asridharan @rajatchopra @caseydavenport
=> api/plugins: implement ordered plugin chaining

SPEC.md, cnitool/cni.go, libcni/api.go, pkg/invoke/delegate.go
Hardcoding the list separator character as ":" causes CNI to fail when parsing
CNI_PATH on other operating systems. For example, Windows uses ";" as list
separator because ":" can legally appear in paths such as "C:\path\to\file".
Fixes #358
=> libcni, pkg\invoke: Use OS-specific list separator when parsing CNI_PATH

pkg/utils/sysctl/sysctl_linux.go
Refs https://github.com/containernetworking/cni/pull/361#issuecomment-277118065.
=> pkg/utils/sysctl/sysctl_linux.go: couple fixes

pkg/invoke/find.go, pkg/invoke/find_test.go, pkg/invoke/os_unix.go, pkg/invoke/os_windows.go
A CNI network configuration file contains the plugin's executable file name.
Some platforms like Windows require a file name extension for executables.
This causes unnecessary burden on admins as they now have to maintain two
versions of each type of netconfig file, which differ only by the ".exe"
extension. A much simpler design is for find package to also look for
well-known extensions. This is done only after checking without the extension,
so no behavioral difference is introduced. Tests are improved and new cases
are added to cover the new behavior.
Fixes #360
=> invoke: Enable plugin file names with extensions

CONVENTIONS.md
After discussion with the CNI maintainers and representatives from Mesos and Kubernetes we've settled on this approach for passing the dynamic port mapping information from runtimes to plugins.
Including it in the plugin config allows "operators" to signal that they expect port mapping information to be passed to a specific plugin (or plugins). This follows the model that config passed in the plugin config should be acted upon by a plugin.
Runtimes can optionally return an error to users if they find no plugin in the chain that supports port mappings.
I'm sure we'd all like to see this merged soon so I'll try to turn any feedback quickly (and I'm happy to get any and all feedback - spellings, unclear working, wrong JSON terminology etc..)
=> CONVENTIONS.md: Update details on port-mappings

README.md
refer #343 issue. Blog regarding Multus CNI usage http://dougbtv.com/nfvpe/2017/02/22/multus-cni/
=> README: List multus as 3rd party plugin

CONVENTIONS.md, SPEC.md, libcni/api.go, libcni/api_test.go, libcni/conf.go, libcni/conf_test.go, pkg/types/types.go
And "runtime_config"->"runtimeConfig" to make capitalizatoin consistent
with other CNI config keys like "cniVersion" and such.
=> spec,libcni: add support for injecting runtimeConfig into plugin stdin data

plugins/ipam/host-local/backend/allocator/config.go
If we don't check it, crash will be observed like this:
`cat /etc/cni/net.d/10-mynet.conf
{
"cniVersion": "0.2.0",
"name": "mynet",
"type": "bridge",
"bridge": "cni0",
"isGateway": true,
"ipMasq": true
}
$ export  CNI_PATH=$GOPATH/src/github.com/containernetworking/cni/bin/
$ export CNI_COMMAND=ADD
$ export CNI_NETNS=/var/run/test
$ export CNI_IFNAME=eth0
$ export CNI_ARGS="FOO=BAR;ABC=123"
$ $GOPATH/src/github.com/containernetworking/cni/bin/host-local < /etc/cni/net.d/10-mynet.conf
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x461416]
goroutine 1 [running]:
panic(0x50e620, 0xc42000c120)
/usr/local/go/src/runtime/panic.go:500 +0x1a1
github.com/containernetworking/cni/plugins/ipam/host-local/backend/al …
=> Check n.IPAM before use it in LoadIPAMConfig function

plugins/ipam/host-local/backend/allocator/allocator.go, plugins/ipam/host-local/backend/disk/backend.go, plugins/ipam/host-local/host_local_suite_test.go, plugins/ipam/host-local/host_local_test.go
When using the `host-local` IPAM plugin, after initial network creation the following error is printed due to missing file:
```
2017/02/03 17:50:08 Error retriving last reserved ip: Failed to retrieve last reserved ip: open /var/lib/cni/networks/external/last_reserved_ip: no such file or directory
```
This fixes to not return an error when the file does not exist.
=> Do not error if last reserved not found after initial creation

pkg/ip/link.go, pkg/ip/link_test.go, plugins/main/bridge/bridge.go, plugins/main/ptp/ptp.go
The exported function SetupVeth now returns a package-defined type.
Addresses #395.
cc: @rosenhouse
=> pkg/ip: do not leak types from vendored netlink package

plugins/meta/flannel/flannel.go, plugins/meta/flannel/flannel_test.go
Based on the CNI spec, if resources are missing we should not always return error (https://github.com/containernetworking/cni/blob/master/SPEC.md#network-configuration-list-error-handling).
An open question on my end would be if that delegates would still need to be called. My thinking is that if we can't read the config - all information that would have been passed down doesn't exist - so we may as well exit early.
Additionally, other plugins may need to be checked for the same conformance against DEL spec expectations.
=> plugins/meta/flannel: If net config is missing do not return err on DEL

README.md
CNI-Genie enables orchestrators (kubernetes, mesos) for seamless connectivity to choice of CNI plugins (calico, canal, romana, weave) configured on a Node. Without CNI-Genie, kubelet is bound to a signle CNI plugin passed to kubelet on start. CNI-Genie allows for multiple CNI plugins being available to kubelet simultaneously.
=> Added entry for CNI-Genie

Documentation/spec-upgrades.md, SPEC.md, libcni/api_test.go, libcni/conf_test.go, pkg/invoke/exec_test.go, pkg/invoke/raw_exec_test.go, pkg/skel/skel_test.go, pkg/types/current/types.go, pkg/types/current/types_test.go, pkg/version/version.go, plugins/ipam/host-local/host_local_test.go, plugins/main/bridge/bridge_test.go, plugins/main/ipvlan/ipvlan_test.go, plugins/main/macvlan/macvlan_test.go, plugins/main/ptp/ptp_test.go, plugins/test/noop/main.go, plugins/test/noop/noop_test.go
Fix a spec omission in https://github.com/containernetworking/cni/pull/145 that forgot to change on instance of 'ip' to 'ips', bump the spec version and update all the plugins to the new spec.  Adds a single testcase for the bridge plugin to ensure compatibility between 0.3.0 and 0.3.1.
=> spec/plugins: fix 'ip'->'ips' in the spec, bump to 0.3.1

README.md
Hi, I'm following the README to get familiar with CNI, and then find out a typo in sectio `How do I use the CNI`. See `git diff` for details.
=> README: build the plugins using ./build.sh, not ./build

plugins/ipam/host-local/backend/allocator/allocator.go, plugins/ipam/host-local/backend/allocator/allocator_test.go
If we run plugin like this, 10.1.0.0 is allocated for use. which is the wrong way：
`
{
"cniVersion": "0.2.0",
"name": "mynet",
"type": "bridge",
"bridge": "cni10",
"isGateway": true,
"ipMasq": true,
"ipam": {
"type": "host-local",
"subnet": "10.1.0.0/16",
"rangeStart": "10.1.0.0",
"rangeEnd": "10.1.255.255",
"gateway": "10.1.0.1"
}
}
export CNI_PATH=$GOPATH/src/github.com/containernetworking/cni/bin/
export CNI_COMMAND=ADD
export CNI_NETNS=/var/run/test
export CNI_IFNAME=eth0
export CNI_ARGS="FOO=BAR;ABC=123"
$GOPATH/src/github.com/containernetworking/cni/bin/host-local < /etc/cni/net.d/10-mynet.conf
2017/03/06 16:44:55 Error retriving last reserved ip: Failed to retrieve last reserved ip: open /var/lib/cni/networks/mynet/last_reserved_ip: no such file or directory
{
"ip4": {
"ip": …
=> Validate rangeStart and rangeEnd specified in conf

cnitool/cni.go
This PR adds capability args to cnitool, which will help to pass capability args for portmapping plugin (https://github.com/containernetworking/plugins/pull/1).
```
$ export CAP_ARGS='{
"portMappings": [
{
"hostPort":      9090,
"containerPort": 80,
"protocol":      "tcp",
"hostIP":        "127.0.0.1"
}
]
}'
$ cnitool add mynet /var/run/netns/myns
```
cc/ @squeed @dcbw
=> cnitool: support capablity args

scripts/docker-run.sh
Hi, if users do `Running a Docker container with network namespace set up by CNI plugins` by following steps in README, then after this, they'll get a dead net container (busybox) left on their environments.
I'm thinking that it would be better if we clean that dead container up and leave the users' environments as clean as before. See `git diff`.
=> scripts: cleanup() should rm net container in docker-run.sh

SPEC.md
JSON example is invalid. Has an extra `,`
=> Fix invalid json

libcni/api_test.go, pkg/types/020/types.go, pkg/types/020/types_test.go, pkg/types/current/types.go, pkg/types/current/types_test.go, plugins/test/noop/noop_test.go
According to [spec](https://github.com/containernetworking/cni/blob/master/SPEC.md#result), plugins should report cniVersion in Result.
Fixes #444.
```sh
$echo '{"cniVersion": "0.3.1","name": "mynet","type": "macvlan","bridge": "cni0","isGateway": true,"ipMasq": true,"ipam": {"type": "host-local","subnet": "10.244.1.0/24","routes": [{ "dst": "0.0.0.0/0" }]}}' | sudo CNI_COMMAND=ADD CNI_NETNS=/var/run/netns/a CNI_PATH=./bin CNI_IFNAME=eth0 CNI_CONTAINERID=a CNI_VERSION=0.3.1 ./bin/bridge
{
"cniVersion": "0.3.1",
"interfaces": [
{
"name": "cni0",
"mac": "0a:58:0a:f4:01:01"
},
{
"name": "veth7c5a44d1",
"mac": "ae:4b:be:d5:7e:88"
},
{
"name": "eth0",
"mac": "0a:58:0a:f4:01:06",
"sandbox": "/var/run/netns/a"
}
],
"ips": [
{
"version": "4",
"interface": 2,
"address": "10.244.1.6/24",
"gateway": …
```
=> Add cniVersion to Result

SPEC.md
`cniVersion` is specified `0.3.1` but the IP structure is from older CNI spec versions [`"ip4"` instead of `"ips"` with its list, etc.]
=> cniVersion and config structure mismatch

README.md
OpenShift uses CNI, so I thought a link to the appropriate docs made
sense in the top-level readme where it lists the other supporting
runtimes.
=> Add OpenShift to the list of container runtimes that support CNI

pkg/invoke/args.go, pkg/invoke/args_test.go
Ensure that custom values take priority over values defined in the
environment by pre-pending them to the env, not appending.
closes #410
=> pkg/invoke: ensure that custom env vars are prepended to the env

README.md
Update README.md to call out how to use priv-net-run.sh and
docker-run.sh scripts post plugin split.
Signed-off-by: Manohar Castelino <manohar.r.castelino@intel.com>
=> Documentation: Update README.md to reflect plugin split

CONVENTIONS.md
Fixes #429 
Note I'm using the phrase "release of the spec" to try to accommodate the fact that changes to the spec were made between 0.1.0 and 0.2.0, but the first spec you should consider "released" with `args` in it is the 0.4.0 tag in this repo.
=> Clarify first released spec with 'args' was 0.2.0

README.md
CNCF projects are required to reference CNCF in the README / website.
Signed-off-by: Chris Aniszczyk <caniszczyk@gmail.com>
=> Add CNCF reference in README

pkg/invoke/raw_exec.go, pkg/types/types.go
This way, we can use Error.Code attribute to check error type without
needing to regexp the message string
kubernetes/kubernetes#43014
=> Return cni.type.Error instead of plain error

pkg/types/current/types.go, pkg/types/current/types_test.go
Plugins that don't have knowledge of interfaces, like host-local or
other IPAM plugins, should not set the 'interfaces' key of their
returned "Result" JSON.  This should then not be translated into
an interface index of 0, which it was due to the int marshaling and
omitempty.
Instead, ensure that an omitted 'interface' in JSON ends up being
-1 in the IPConfig structure, and that a -1 ensures that no 'interfaces'
key is present in the JSON.
Yes, this means that you must set Interface:-1 in IPConfig in your
plugin, but if you weren't already doing that and your plugin didn't
deal with interface indexes, you already had a problem.
@containernetworking/cni-maintainers 
A bit ugly, but we can't also change the IPConfig.Interface field to a *int because then it's really, really icky to actually …
=> types: fix marshalling of omitted "interfaces" key in IPConfig JSON

pkg/types/args.go, pkg/types/args_test.go
`types.LoadArgs()` does an unsafe typecast for env args key value pairs.
This can cause a panic if the config type fields do not implement
the `encoding.TextUnmarshaler` interface. This commit modifies it to
do a safe type cast and return an error in such scenarios.
* Added a new unit test that would panic without this code-change, which passes now
* `./test.sh` succeeds as well
1. Test Panic without the code change
```bash
$ go test ./pkg/types/
Running Suite: Types Suite
==========================
Random Seed: 1495483401
Will run 12 of 12 specs
•••••
------------------------------
•! Panic [0.000 seconds]
LoadArgs
/home/ec2-user/workspace/src/github.com/containernetworking/cni/pkg/types/args_test.go:134
When known arguments are passed and cannot be unmarshalled …
```
=> pkg/types: return error instead of crashing when code supplies an incompatible type to types.LoadArgs() 

CONVENTIONS.md
This is a change to CONVENTIONS that states, essentially, that plugins SHOULD be chained if at all possible. The intention is to support the widest-possible set of users.
=> Conventions: add convention around chaining interfaces

cnitool/cni.go
This PR add `CNI_ARGS` support in cnitool, so as to facilitate plugins required this environment variable.
=> cnitool: add support for CNI_ARGS

README.md
Hi, I built this plugin for overlay networks with Open vSwitch. It mainly focuses on 
SDN/OpenFlow network and supports for adding SDN controller such as ONOS, Ryu and 
OpenDaylight by configuring network configuration.
=> README plugins list: add Linen CNI plugin

SPEC.md
=> Spec lists git tags pointing to old spec versions

libcni/conf.go, libcni/conf_test.go
A network config missing Type is pretty useless since it means we can't
find the plugin to execute.  So return an error if Type isn't given.
@containernetworking/cni-maintainers @squeed
=> libcni: return error if Type is empty

pkg/skel/skel.go, pkg/skel/skel_test.go
Right now, I have to do the following
$ echo | CNI_COMMAND=VERSION bridge
or
CNI_COMMAND=VERSION bridge
^D
to be able to get the result back.
But VERSION doesn't need to read from stdin.
=> skel: VERSION shouldn't block on stdin

CONVENTIONS.md, SPEC.md
I've erred on the side of doing less rather than more here, but a few things struck me while making the change.  I don't think this PR is ready yet; but I think it's far enough for discussion.
The specification does leave quite a lot of wiggle room.  I haven't tried to remove this, because it's more than just a clarification - the general theme is that there's quite a lot of flexibility in interpretation and use of the various parameters, especially around extending the core spec.  Interoperability is partially sacrificed for flexibility (and ease of implementation) - this is made clear in conventions.md, particularly.
Before going all the way down this road, I think a position on how precise the spec should be is needed.
=> Use more RFC2119 style language in specification (must, should...)

README.md
We like to add [Vhostuser CNI](https://github.com/intel/vhost-user-net-plugin) as a 3rd party plugin in CNI. Vhostuser plugin is a Container Network Interface (CNI) plugin to run with OVS-DPDK and VPP along with [Multus CNI](https://github.com/Intel-Corp/multus-cni) plugin in Kubernetes for Bare metal container deployment model. It enhances high performance container Networking solution and Dataplane Acceleration for NFV Environment.
=> README: List vhostuser CNI as a 3rd party plugin

SPEC.md
@containernetworking/cni-maintainers @caseydavenport
=> spec: add notes about ADD/DEL ordering

CONVENTIONS.md
The `host-local` ipam plugin now supports the `ips` field in `args`. Document that.
Fixes: #303
=> Conventions: add the "ips" arg

.travis.yml, Vagrantfile, pkg/invoke/delegate_test.go
Go 1.9 is out, 1.7 is now no longer maintained.
Reference: https://golang.org/doc/devel/release.html#policy
See also: https://github.com/containernetworking/plugins/pull/65
=> Golang versions: add 1.9, drop 1.7

SPEC.md, pkg/invoke/delegate_test.go, pkg/skel/skel.go, pkg/skel/skel_test.go
Previously, the spec did not require the container id to be set. However, almost every plugin relies on it being unique, including the CNI-maintained plugins. So, change the spec to require the use of container id and that plugins should treat it as a primary key.
=> spec, skel: Make the container ID required and unique.

cnitool/README.md, cnitool/cnitool.go
We shouldn't be creating networks with a blank containerid. Let's synthesize one from the netns path.
=> cnitool: generate container id from the netns path

README.md
Amazon ECS uses the following CNI plugins for provisioning Amazon EC2 elastic network interfaces (ENIs) to containers (more information [here](http://docs.aws.amazon.com/AmazonECS/latest/developerguide/task-networking.html):
* [ecs-eni](https://github.com/aws/amazon-ecs-cni-plugins/tree/master/plugins/eni)
* [ecs-bridge](https://github.com/aws/amazon-ecs-cni-plugins/tree/master/plugins/ecs-bridge)
* [ecs-ipam](https://github.com/aws/amazon-ecs-cni-plugins/tree/master/plugins/ecs-bridge)
This PR adds references to the same in README
=> readme: add Amazon ECS to runtimes and plugins list

pkg/types/current/types_test.go, pkg/types/types.go, pkg/types/types_test.go
bonus:  non-pointer instances of `types.Route` now correctly marshal to JSON
=> backfill some unit tests

README.md
Kurma is a derelict project so should be removed because the link just redirects to apcera.com.
=> kurma is no longer maintained

README.md
- [Bonding CNI](https://github.com/Intel-Corp/bond-cni) provides a method for aggregating multiple network interfaces into a single logical "bonded" interface.
- Linx Bonding drivers provides various flavour of bonded interface depending on the mode (bonding policies), such as round robin, active aggregation according to the 802.3 ad specification
For more information on the bonding driver. Please refer to [kernel doc](https://www.kernel.org/doc/Documentation/networking/bonding.txt)
=> Adding the Bonding CNI plugin as 3rd party plugin

pkg/types/types.go
IPAM is now a concrete type. Was considering testing all of the types.go package, thoughts?
closes #95
=> pkg/types: Makes IPAM concrete type

CONVENTIONS.md
Fix a typo when reading CONVENTIONS.md
=> Fix typo in CONVENTIONS.md

.travis.yml, pkg/version/legacy_examples/example_runtime.go, test.sh
The legacy example plugin and its libcni backwards_compatibility_test.go
just use the noop plugin, which doesn't do anything with the netns path
or make any interfaces inside the netns.  So we can remove anything
netns related from the test, which means we no longer need sudo.
=> tests: sudo not actually required

.travis.yml, Vagrantfile
- test against Go 1.10
- stop testing against Go 1.8
since Go language maintainers no longer support 1.8
see: https://golang.org/doc/devel/release.html#policy
=> travis: bump golang versions

SPEC.md
Might be an historical artefact but I believe the correct full name for CNI should be Container Network Interface 
CC: @bboreham
=> fixes the title in specification

SPEC.md
The CNI spec version passed from runtime to plugin is the `cniVersion`
field in the network configuration rather than a parameter to the ADD
and DEL command. So, remove the version parameter from the spec, and
also describe how the `cniVersion` field in the network configuration
should be used by the plugin.
Fixes #542
=> spec: remove the version parameter from ADD and DEL commands.

pkg/invoke/get_version_integration_test.go, pkg/skel/skel.go, pkg/skel/skel_test.go, plugins/test/noop/main.go
This adds an additional argument to PluginMain, the `about` field. It is emitted on stderr when CNI_COMMAND is not provided.
This is for the ease of administrators.
=> skel: add support for plugin version string

cnitool/cnitool.go, libcni/api.go, libcni/api_test.go, libcni/backwards_compatibility_test.go, pkg/invoke/args_test.go, pkg/invoke/delegate.go, pkg/invoke/delegate_test.go, pkg/invoke/exec.go, pkg/invoke/exec_test.go, pkg/invoke/fakes/raw_exec.go, pkg/invoke/get_version_integration_test.go, pkg/invoke/raw_exec.go
When a downstream project just uses libcni, it takes a lot of harness
code to set up binaries on-disk that get called.  Instead we can handle
that by passing an execer interface to libcni APIs that gets called
instead, which the downstreams can use to avoid execing thing entirely
and instead check arguments/environment in code.
@containernetworking/cni-maintainers @squeed
=> libcni: make exec handling an interface for better downstream testing

libcni/api.go, libcni/api_test.go
These perform some static validation on a network configuration, ensuring it is generally executable.
Fixes: #523
=> libcni: add ValidateNetwork and ValidateNetworkList functions

README.md
This change is to update the 3rd Party plugin section of README
to include and list the K8s CNI solution from Juniper Networks, INC.
=> Add Juniper Contrail to 3rd party plugin list

README.md
If there were no name field in 99-loopback.conf, there would be an error:
```
root@iZ2ze8rkx46zyx6mojyeb5Z:~/gocode/src/github.com/containernetworking/cni/scripts# ./priv-net-run.sh ifconfig
null : error executing ADD: missing network name
```
=> Add name field in 99-loopback.conf because network name is required.

README.md
This PR adds Knitter to 3rd party plugin list in README. Knitter is a CNI plugin supporting multiple networking for Kubernetes.
=> List Knitter as 3rd party plugin

pkg/types/types.go, pkg/version/version.go, pkg/version/version_test.go
Plugins can use the new helpers to parse a prevResult.  When parsing
their NetConf structure, assuming it has a types.NetConf embedded:
```golang
type MyConf struct {
types.NetConf
...
}
conf := MyConf{}
if err := json.Unmarshal(stdin, &conf); err != nil {
return nil, fmt.Errorf("failed to parse network configuration: %v", err)
}
if err := version.ParsePrevResult(&conf.NetConf); err != nil {
return nil, err
}
```
and then when the plugin wishes to access the PrevResult it can transform
conf.PrevResult into any Result version it wants:
```golang
if conf.PrevResult != nil {
res, err := current.NewResultFromResult(conf.PrevResult)
if err != nil {
return nil, fmt.Errorf("could not convert result to current version: %v", err)
}
for _, ip := range res.IPs {
...
}
}
``` …
=> types/version: add helper to parse PrevResult

pkg/types/current/types.go
Signed-off-by: Lifubang <lifubang@aliyun.com>
issue: https://github.com/containerd/containerd/issues/2540
When type is loopback, and cniVersion is 0.2.0, the NewResultFromResult will return an error:
cannot convert: no valid IP addresses
I think we should not check IPs field in method convertFrom020. Let it check by user. Because all have been successful except this check.
Please check it, thanks.
=> when type is loopback, IP4 or IP6 is always nil

SPEC.md
This follows the CHECK spec we drafted in the maintainers call a couple of weeks ago.  
This provides a CHECK feature to make sure networking seems to be in a good state - it doesn't provide a mechanism for communicating changes in networking (e.g. a different DHCP leased IP).  That's something that will need a bit more thought and seems easier to allow later than to close the door on if we do it wrong.
=> Replace GET action in spec with proposed CHECK action

cnitool/cnitool.go
cnitool:  Honor interface name supplied via CNI_IFNAME environment variable.
Use interface name supplied via CNI_IFNAME environment variable, when set.  Default to eth0 otherwise.
Fixes: #586
=> cnitool: Honor interface name supplied via CNI_IFNAME environment variable.

cnitool/cnitool.go, libcni/api.go, libcni/api_test.go, libcni/conf.go, libcni/conf_test.go, pkg/invoke/delegate.go, pkg/invoke/delegate_test.go, pkg/invoke/get_version_integration_test.go, pkg/skel/skel.go, pkg/skel/skel_test.go, pkg/types/types.go, plugins/test/noop/main.go
Major change is that CHECK no longer returns a Result, per the spec.
@squeed @containernetworking/cni-maintainers @mcctcpip @jellonek
=> skel,invoke,libcni: GET -> CHECK

SPEC.md
This came up in the maintainers' meeting - in the (rare, unspecified) cases that a plugin wants the runtime to re-try the operation it can have a special code to say that.
=> Add a well-known error for "try again"

SPEC.md
This paragraph was under a heading specifically about configuration lists, but it applies to all DEL operations whether in a list or not.
=> Move spec text about DEL and errors

libcni/api.go, libcni/api_test.go
Fix some typos:
1. "exmaple" -> "example".
2.  "inaccessble" -> "inaccessible".
=> Fix some typos

cnitool/cnitool.go
Currently, cnitool command needs 4 args (including command itself) - e.g cnitool add `<net>`
`<netns>`. This patch changes to the number of valide args to 4 from 3.
For example, currently if cnitool runs with less args, it will get gopanic instead of validation error and usage help:
~~~
$ sudo CNI_PATH=./bin/  ~/.go/bin/cnitool add dbnet
panic: runtime error: index out of range
goroutine 1 [running]:
main.main()
/home/knakayam/.go/src/github.com/containernetworking/cni/cnitool/cnitool.go:96 +0x799
~~~
=> Validate correct number of args in cnitool

README.md
Commit containernetworking/plugins@4e1f780 (Split build.sh into two OS-specific scripts) removes the `build.sh` file. Now we have `build_linux.sh` and `build_windows.sh`.
Signed-off-by: Radostin Stoyanov <rstoyanov1@gmail.com>
=> readme: Update CNI plugins install example

pkg/types/current/types_test.go, pkg/types/types.go
1. "unmarshaling" to "unmarshalling" in line 240.
2. "verison" to "version" in line 90.
=> Fix some typos in comment

SPEC.md
1. "extentions" to "extensions" in line 30.
2. "preceeding" to "preceding" in line 98 and 120.
=> Fix some typos in SPEC.md

cnitool/README.md
build.sh script doesn't exist anymore change to build_linux.sh or
build_windows.sh
=> Fix cnitool readme

CONTRIBUTING.md, README.md, SPEC.md
For security, we should change http into https links.
=> Change http to https for security links

pkg/types/020/types.go, pkg/types/current/types.go, pkg/types/types.go
add `PrintTo` method to `Result` interface, in order to allow to marshal result to any writer, not only stdout
=> add PrintTo method to Result interface

SPEC.md
Current, the URLs that link docs of **rkt_networking_proposal** and
**rkt_networking_design** are already dead. So this commit aims to
clean up them from **SPEC.md**.
Co-Authored-By: Nguyen Phuong An <AnNP@vn.fujitsu.com>
Signed-off-by: Kim Bao Long <longkb@vn.fujitsu.com>
=> Remove deprecated link in SPEC.md

pkg/types/current/types.go, pkg/types/current/types_test.go
When converting from 0.2.0 to 0.3.x, we used to copy the Gateway defined
under IP4.Gateway to each route that had GW set to nil. This is wrong
because the result of converting from 0.2.0 to 0.3.x and back to 0.2.0
doesn't match the original config.
Also, the spec says the following about routes.gw: "IP of the gateway.
If omitted, a default gateway is assumed (as determined by the CNI
plugin)."
So, it should be up to the CNI plugin to determine what to do when the
gateway in a route isn't specified. Therefore, when converting from
0.2.0 to 0.3.x, we should NOT populate the gateway field.
=> Don't copy gw from IP4.Gateway to Route.GW When converting from 0.2.0

SPEC.md
Routes are expected to be relevant to the sandbox interface.
=> SPEC.md: clarify meaning of 'routes'

CONVENTIONS.md
Although it is spelling mistakes, it might make
affects while reading.
Signed-off-by: Nguyen Hai Truong <truongnh@vn.fujitsu.com>
=> doc: fix typo

SPEC.md
Some links in SPEC document is not available so I remove them.
=> Remove incorrect document link

Documentation/spec-upgrades.md
Currently, the modified **plugins/main** was removed from master branch.
It's only available in **v0.3.0** tag. So this commit aims to update the
deprecated link to the working one.
Co-Authored-By: Nguyen Phuong An <AnNP@vn.fujitsu.com>
Signed-off-by: Kim Bao Long <longkb@vn.fujitsu.com>
=> Update deprecated link in doc

CONVENTIONS.md
While many plugins already have IPAM range info not all do. Without
a range/subnet in configuration, passing a plain IP address in
CNI_ARGS or via 'args' does not provide enough information.
=> CONVENTIONS: add support for IP prefixes

Documentation/spec-upgrades.md
I found that `Library and Plugins Release v0.5.0` just linked to the latest release page.
The link address does not match the link description.
So I fixed it.
=> Make link point to the correct version

libcni/api_test.go, pkg/invoke/raw_exec.go
was seeing some
Failed create pod sandbox: rpc error: code = Unknown desc = failed to
create pod network sandbox k8s_kube-controller-manager-operator-54c6d7
69f4-2rnzn_openshift-kube-controller-manager-operator_1f508e1a-5d25-11
e9-b0ba-024239aadba4_0(19273c65ace39e557bcf7097e457a358ca52e4cb193388e
b3bda13d5143c955d): netplugin failed but error parsing its diagnostic
message \"\": unexpected end of JSON input",
and thought, that's a pretty lame error message.
(Maybe also change "netplugin" to "network plugin"? Also, as suggested by the tests, this might specifically mean "the plugin timed out", but maybe we should arrange to have an error message that states that explicitly if that happens?)
=> Return a better error when the plugin returns none

pkg/invoke/args.go, pkg/invoke/args_test.go
From this commit [https://github.com/golang/go/commit/e73f4894949c4ced611881329ff8f37805152585#diff-2f929a7660c606fd0c5b268dad1a9bd4R61](https://github.com/golang/go/commit/e73f4894949c4ced611881329ff8f37805152585#diff-2f929a7660c606fd0c5b268dad1a9bd4R61) in golang, we can know that the RawExec will clean the duplicated envs and keep the last valid env of the same key.
So if we want to prepend custom args from CNIArgs rather than the existing process environments, we should append custom args in the end.
=> invoke : ensure custom envs of CNIArgs are prepended to process envs

pkg/invoke/args.go, pkg/invoke/args_test.go, pkg/invoke/delegate.go, pkg/invoke/delegate_test.go
Sometimes, we need a DEL exec for another CNI plugin in a main CNI plugin process, such as a ipam revert in ADD exec of macvlan plugin (ref to discussions in  [https://github.com/containernetworking/plugins/pull/301](https://github.com/containernetworking/plugins/pull/301)), in this scenario, I think delegation func should have the ability to override CNI_COMMAND env in process environments heritance automatically. This will help us to avoid setting and unsetting CNI_COMMAND env again and again.
=> delegate : allow delegation funcs override CNI_COMMAND env automatically in heritance

README.md
Changed wording and typos in the main README.md
=> Docs: Small typo fixes in main README.md

libcni/api.go, libcni/api_test.go, libcni/backwards_compatibility_test.go
CacheDir is a property of the entire CNIConfig object and there is no
point to having it be different between container invocations. It was
originally put in RuntimeConfig to make re-vendoring easier so that
users wouldn't have to update calls to InitCNIConfig.
=> libcni: add InitCNIConfigWithCacheDir() and deprecate RuntimeConfig.CacheDir

libcni/api_test.go, libcni/conf.go, pkg/invoke/args.go, pkg/types/args.go, pkg/types/types.go, plugins/test/noop/main.go
ref to [https://github.com/containernetworking/cni/issues/642](https://github.com/containernetworking/cni/issues/642)
try to fix some warnings generated by [staticcheck](https://staticcheck.io/)
=> clean up : fix staticcheck warnings

libcni/api.go
Function `validatePlugin` in libcni should find plugin by `exec.FindInPath` instead of using `invoke.FindInPath` directly, just like `addNetwork` [https://github.com/containernetworking/cni/blob/df124b22e4f7a0b716d313884aee6474b319b4a3/libcni/api.go#L378](https://github.com/containernetworking/cni/blob/df124b22e4f7a0b716d313884aee6474b319b4a3/libcni/api.go#L378).
I think this breaks CI of [https://github.com/cri-o/ocicni/pull/51](https://github.com/cri-o/ocicni/pull/51).
=> libcni: find plugin in exec

SPEC.md, pkg/skel/skel.go, pkg/skel/skel_test.go, pkg/types/types.go, pkg/types/types_test.go, plugins/test/noop/noop_test.go
=> skel: clean up errors in skel and add some well-known error codes

libcni/api.go
The structure member name was changed from Results -> Result during
review but we missed changing the JSON key name.  Fix that and fall
back to the old name if required.
@containernetworking/cni-maintainers @bboreham @jellonek @squeed
=> libcni: fix cache file 'result' key name

SPEC.md, libcni/api.go, libcni/api_test.go, pkg/skel/skel.go, pkg/skel/skel_test.go, pkg/utils/utils.go
validate containerID and networkName
ensure they contain only letters and numbers
Fixes https://github.com/containernetworking/cni/issues/679
=> validate containerID and networkName

libcni/api.go, libcni/api_test.go
We should have all components of the uniqueness tuple in the cache file
so that they can be read out of the file without trying to parse the
cache file name.
@bboreham @jellonek @squeed @containernetworking/cni-maintainers
=> libcni: also cache IfName

SPEC.md
I was confused about some lines when I read `CNI CHECK` section in SPEC.md for adding check function to loopback plugin.
I think the lines which I changed should be a whole sentence but not a list, because list is more proper for some "parallel" things.
=> spec: fix some typo in docs

SPEC.md, libcni/api.go, libcni/api_test.go, pkg/skel/skel.go, pkg/skel/skel_test.go, pkg/utils/utils.go
Interface name in linux is not unrestricted, so bad interface name will break CNI plugin.
This pr will add interface name validation to libcni and skel.
validation rules ref to [https://github.com/torvalds/linux/blob/master/net/core/dev.c#L1024](https://github.com/torvalds/linux/blob/master/net/core/dev.c#L1024)
=> add interface name validation

libcni/api.go, libcni/api_test.go
When CNI version isn't supplied in config, use default.
Fixes [720](https://github.com/containernetworking/cni/issues/720)
Signed-off-by: Michael Cambria <mccv1r0@gmail.com>
=> When CNI version isn't supplied in config, use default.

SPEC.md
The specification is good but I found it a bit hard to navigate because it's quite long. So I added a hyperlinked table of contents to the beginning of the document.
The Markdown for the table of contents has been automatically generated with [markdown-toc](https://github.com/jonschlinkert/markdown-toc):
```bash
markdown-toc --no-firsth1 --maxdepth=2 SPEC.md
```
And then pasted into the file.
See here [how it looks like](https://github.com/weibeld/cni/blob/master/SPEC.md).
=> Add table of contents to SPEC.md

CONTRIBUTING.md, Vagrantfile
This change addresses a few missing steps and out-of-date items in the
contributor docs such as fetching proper dependencies and removing
references to paths that no longer exist.
Fixes #726
=> DOCUMENTATION: Address incomplete instructions in CONTRIBUTING.md

pkg/invoke/raw_exec.go
fixes https://github.com/containernetworking/cni/issues/732
=> intercept netplugin std error

pkg/utils/utils_test.go
Add corresponding unit tests to the functions in util.go.
Signed-off-by: Zhou Hao <zhouhao@cn.fujitsu.com>
=> pkg/utils: add utils_test

SPEC.md
`json` identifier cannot handle json with comments well. Change the identifier to `jsonc`.
Ref: github/linguist#4153
=> Change language identifier to jsonc for json with comments

pkg/utils/utils_test.go
A follow-up fix PR of #736 , IMO, we should use black-box testing for our utility functions.
=> pkg/utils: utility package should use black-box testing

pkg/types/020/types.go, pkg/types/020/types_test.go, pkg/types/current/types.go, pkg/types/current/types_test.go, pkg/types/types.go
`String()` of `Result` declared in `pkg/types/types.go` should return a `Result`
representation in JSON, instead of custom formatted string, which
additionally is not in the same form as described in docstring, which also e.g. is missing `Routes` part.
This PR changes this behavior to be consistent with behavior documented in the interface.
As `String()` interface does not have any place for errors - if there
would be any - instead of JSON value output will be an empty string.
Closes #581
_edit/update:_
As discussed in comments - this PR removes funcs which are turning `Result` to string.
=> Update Result.String implementation to work as declared in interface

ROADMAP.md
0.6.0 is done.
CHECK is done.
We set a goal to get 1.0 shipped for Kubecon EU, so moved some steps out beyond that.
=> Update roadmap for 1.0 plans

CONTRIBUTING.md
The domain `freenode.org` is no longer up-to-date,
use `freenode.net` instead
Signed-off-by: Nguyen Hai Truong <truongnh@vn.fujitsu.com>
=> Update link freenode.org to freenode.net

SPEC.md
I tried to drive my plugin with the provided examples in the SPECS.md and found that some of them are invalid JSONs due to some extra chars in the lists.
Note: Some of them still contains some comments in `//` format, which is also invalid in JSON.
=> Remove extra ',' chars which makes conflist examples invalid.

CONVENTIONS.md
This commit extends CONVENTION.md Well-known Capabilities
to inclue `guid`. this shall be used by CNI plugins who wish
to set Infiniband GUID address for a network interface.
This addresses issue #741
=> Add GUID to well known Capabilities

libcni/api_test.go, pkg/invoke/raw_exec.go, pkg/invoke/raw_exec_test.go, plugins/test/noop/debug/debug.go, plugins/test/noop/main.go, plugins/test/noop/noop_test.go, test.sh
The way raw_exec invokes the command doesn't actually pass back
stderr, despite ExitError having that capability.  c.Run()
internally calls c.Wait() but that doesn't capture stderr and
insert it into the returned ExitError. So we have to do that
ourselves.
Fixes: https://github.com/containernetworking/cni/issues/732
Fixes: https://github.com/containernetworking/cni/pull/759
@bboreham @squeed @mccv1r0 @containernetworking/cni-maintainers
=> invoke: capture and return stderr if plugin exits unexpectedly

CONVENTIONS.md
This commit attempts to standardize the consumption
of a device identifier by CNI's for networks that
is associated with a device resource and require its
identifier to perform configurations.
This addresses PR #757
=> Add DeviceID attribute to RuntimeConfig

pkg/invoke/raw_exec.go
This makes the plugin validation a bit more robust by retrying the
execution if the plugin is in text file busy state. This can happen if
we write the config and the plugin at once. To avoid such races we now
try up to 5 seconds for the plugin validation.
=> Retry exec commands on text file busy

README.md
Adding [OVN4NFV-K8S-Plugin](https://github.com/opnfv/ovn4nfv-k8s-plugin) is OVN based CNI controller plugin to provide cloud-native based Service function chaining(SFC), Multiple OVN overlay networking, dynamic subnet creation, dynamic creation of virtual networks, VLAN Provider network, Direct provider network and pluggable with other Multi-network plugins, ideal for edge-based cloud-native workloads in Multi-cluster networking
=> adding OVN4NFV-K8s-Plugin as 3rd party plugin

SPEC.md
#768, in reformatting the errors codes within the specification, changed their values from positive to negative integers (which I assume was not intentional).
=> Revert formatting of error codes

SPEC.md, libcni/api_test.go, pkg/invoke/delegate_test.go, pkg/invoke/exec_test.go, pkg/skel/skel_test.go, pkg/types/020/types.go, pkg/types/020/types_test.go, pkg/types/040/types.go, pkg/types/040/types_suite_test.go, pkg/types/040/types_test.go, pkg/types/100/types.go, pkg/types/100/types_suite_test.go, pkg/types/100/types_test.go, pkg/types/current/types.go, pkg/types/current/types_test.go, pkg/types/internal/convert.go, pkg/types/types.go, pkg/version/version.go, pkg/version/version_test.go, plugins/test/noop/main.go, plugins/test/noop/noop_test.go
Moving to spec 1.0.0 requires more complicated conversions, so
put the converter determination logic in a separate module that
any of the types can call to convert between arbitrary versions.
This is necessary to ensure the types don't have import cycles.
This also implements downconversion, which we never claimed
*not* to support, but didn't implement.
It also verifies that the Result object unmarshalled by
each result type's NewResult() function is actually supported
by the result type. This is a potentially breaking change as
this was not previously done, and for example may now fail
attempts to read a cached PrevResult written by a previous
version.
Signed-off-by: Dan Williams <dcbw@redhat.com>
=> types changes for 1.0.0

pkg/types/020/types.go, pkg/types/040/types.go, pkg/types/100/types.go, pkg/types/create/create.go, pkg/types/internal/convert.go, pkg/types/internal/create.go, pkg/types/types.go, pkg/version/version.go
SupportedVersions isn't really needed outside the types themselves.
@squeed @mccv1r0 @bboreham @matthewdupre
=> types: unexport SupportedVersions

README.md
After kube-ovn became  a CNCF Sandbox Level Project, kube-ovn changed the githubsite from [https://github.com/alauda/kube-ovn] to [https://github.com/kubeovn/kube-ovn]. Follow changes.
=> upgrade kube-ovn new github site

CONVENTIONS.md, SPEC.md
The spec deviated from the existing behavior, and it was never actually implemented in libcni. So this is a no-op.
=> Spec: Bring 1.0's treatment of "args" in line with 0.4.0

MAINTAINERS
I am moving on from Weaveworks, and will not be working in the container networking domain.
=> Remove Bryan Boreham as maintainer

pkg/types/args.go, pkg/types/args_test.go
During the implementation of [https://github.com/containernetworking/plugins/pull/630](https://github.com/containernetworking/plugins/pull/630), I found that field with pointer type `*net.IP` can not be parsed by `LoadArgs`, but this is working on `json.Unmarshal`.
This PR is trying to support both value type and pointer type which have `encoding.TextUnmarshaler` interface in `LoadArgs`.
=> chore: support both value type and pointer type in LoadArgs

libcni/api.go, pkg/invoke/exec.go, pkg/types/create/create.go, pkg/version/conf.go, pkg/version/version.go
Turns out a number of users want to read in JSON and
create a Result object from it, and CNI didn't have
a function to do that in one call. Instead you had to
create a ConfigDecoder first, then create a Result
from the given version.
That's silly, let's just make a function to do that
and let everyone do less work.
@mccv1r0 @mars1024 @squeed @jellonek @jayunit100
=> types/create: add CreateFromBytes()

libcni/api.go, libcni/conf.go, pkg/types/args.go, pkg/types/create/create.go, pkg/version/legacy_examples/example_runtime.go, pkg/version/plugin.go, pkg/version/version.go, plugins/test/noop/main.go
`fmt.Errorf` errors should wrap the original error with `%w`.
This allows the caller to check the errors with `errors.Is()`.
see: https://blog.golang.org/go1.13-errors
=> wrap returned errors

pkg/version/version.go, pkg/version/version_test.go
So plugins can easily declare support for "from version 0.3 and beyond".
=> pkg/version: add VersionsFrom function

pkg/skel/skel.go, pkg/skel/skel_test.go
It was suggested on Twitter that this would clarify things.
=> skel: print out CNI versions supported in help text.

pkg/skel/skel.go
There is no need to check err against nil, just return it.
=> skel: remove superfluous err nil check in (*dispatcher).pluginMain

README.md
The link was pointing to  https://github.com/Intel-Corp/multus-cni for, but that repository is empty (and the readme says "takeover by codermak", on top of that). I think the right link for Multus would be this: https://github.com/k8snetworkplumbingwg/multus-cni .
=> documentation: update Multus link in README.md 

SPEC.md
Explicitly state that the container runtime, not the plugin, shall tear
down network namespaces.
Fixes #872
Signed-off-by: Andreas Karis <ak.karis@gmail.com>
=> Spec: Container runtime shall tear down namespaces

libcni/conf.go, pkg/types/040/types_test.go, pkg/types/100/types_test.go
See https://github.com/howardjohn/go-unmarshal-double-pointer for more
info on why this is not safe and how this is detected.
=> Fix incorrect pointer inputs to `json.Unmarshal`

libcni/backwards_compatibility_test.go, pkg/version/plugin.go, pkg/version/plugin_test.go
Without this Delete failed for empty-version configs.
Update the tests to catch this case.
=> libcni: handle empty version when parsing version

cnitool/cnitool.go
exported const EnvCNIPath should have comment (or a comment on this block) or be unexported
Signed-off-by: Tomoya Fujita <Tomoya.Fujita@sony.com>
=> cnitool: address golint error

pkg/invoke/exec.go, pkg/invoke/exec_test.go
The CNI Spec requires plugins to return a CNIVersion in the Result
that is the same as the CNIVersion of the incoming CNI config.
Empty CNIVersions are specified to map to 0.1.0 (since the first
CNI spec didn't have versioning) and libcni handles that automatically.
Unfortunately some versions of Weave don't do that and depend on
a libcni <= 0.8 quirk that used the netconf version if the result
version was empty. This is technically a libcni regression, though
the plugin itself is violating the specification.
Thus for backwards compatibility assume that if the Result
CNIVersion is empty, the netconf CNIVersion should be used as
the Result version.
Fixes: https://github.com/containernetworking/cni/issues/895
=> invoke: if Result CNIVersion is empty use netconf CNIVersion

pkg/invoke/exec.go
Properly handle "null" as plugin output. This successfully unmarshals to a nil map, which crashes later when assigning confVersion to the map. This regression was introduced in https://github.com/containernetworking/cni/pull/896.
Found when attempting to update multus to v1.1.1; its tests use a dummy plugin output of "null" which causes a panic rather than an error.
```
Test Panicked
assignment to entry in nil map
/usr/lib/go-1.18/src/runtime/map_faststr.go:205
Full Stack Trace
github.com/containernetworking/cni/pkg/invoke.fixupResultVersion({0xc000598000?, 0x18?, 0x1a?}, {0xc000430888, 0x4, 0x8})
/var/lib/repos/go/src/github.com/k8snetworkplumbingwg/multus-cni/vendor/github.com/containernetworking/cni/pkg/invoke/exec.go:65 +0x199 …
```
=> Fix successfully unmarshalled nil raw result

go.mod, go.sum, pkg/ns/ns_linux.go, pkg/ns/ns_windows.go, pkg/skel/skel.go, pkg/types/types.go
fix-714: https://github.com/containernetworking/plugins/issues/714
=> fix 714-plugin add netns validation reinforcement

.github/workflows/commands.yml, .github/workflows/test.yaml
Upgrades actions/checkout and actions/setup-go packages to v3 to resolve CI workflow NodeJS 12 warnings.
https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/
Signed-off-by: Austin Vazquez <macedonv@amazon.com>
=> Upgrade GitHub actions packages to resolve NodeJS 12 warnings

libcni/api.go, libcni/api_test.go, libcni/backwards_compatibility_test.go, libcni/conf.go, libcni/conf_test.go, pkg/invoke/delegate_test.go, pkg/invoke/find_test.go, pkg/invoke/get_version_integration_test.go, pkg/invoke/raw_exec_test.go, pkg/skel/skel.go, pkg/types/040/types_test.go, pkg/types/100/types_test.go, pkg/version/legacy_examples/example_runtime.go, pkg/version/legacy_examples/examples.go, pkg/version/testhelpers/testhelpers.go, pkg/version/testhelpers/testhelpers_test.go, plugins/test/noop/debug/debug.go, plugins/test/noop/main.go, plugins/test/noop/noop_test.go
Recently we have upgraded the Go version in #913. The `io/ioutil` package has been deprecated in Go 1.16 (See https://pkg.go.dev/io/ioutil). This PR replaces the existing `io/ioutil` functions with their new definitions in `io` and `os` packages.
- `ioutil.Discard` => `io.Discard`
- `ioutil.NopCloser` => `io.NopCloser`
- `ioutil.ReadAll` => `io.ReadAll`
- `ioutil.ReadDir` => `os.ReadDir`
- `ioutil.ReadFile` => `os.ReadFile`
- `ioutil.TempDir` => `os.MkdirTemp`
- `ioutil.TempFile` => `os.CreateTemp`
- `ioutil.WriteFile` => `os.WriteFile`
=> refactor: move from io/ioutil to io and os packages

CONVENTIONS.md
Container runtimes can pass pod cgroup paths
when requested by CNI plugins.
Details around the use cases for this field are
documented - https://github.com/kubernetes/kubernetes/issues/113342.
Signed-off-by: Aditi Ghag <aditi@cilium.io>
=> Extend capabilities with cgroup path

README.md
spiderpool: An IP Address Management (IPAM) CNI plugin of Kubernetes for managing static ip for underlay network. Spiderpool can work well with any CNI project that is compatible with third-party IPAM plugins.
Why Spiderpool? Given that there has not yet been a comprehensive, user-friendly and intelligent open source solution for what underlay networks' IPAMs need, Spiderpool comes in to eliminate the complexity of allocating IP addresses to underlay networks.
With the hope of the operations of IP allocation being as simple as some overlay-network CNI, Spiderpool supports many features, such as static application IP addresses, dynamic scalability of IP addresses, multi-NIC, dual-stack support, etc.
Hopefully, Spiderpool will be a new IPAM alternative for open source enthusiasts.
Any CNI …
=> 3rd party plugins - spiderpool

SPEC.md, libcni/api_test.go, pkg/invoke/delegate_test.go, pkg/skel/skel_test.go, pkg/types/100/types.go, pkg/types/100/types_test.go, pkg/version/version.go, pkg/version/version_test.go, plugins/test/noop/main.go
This does a bit of refactoring, since types v1.0.0 also implement the result type for v1.1.0. But nothing too bad.
=> Prepare for spec version v1.1

pkg/types/create/create.go
There was a bug in which some versions didn't register their creation function, thus leaving some types un-decodeable. Fix that by explicitly importing all known versions.
=> pkg/types: explicitly import all versions

.github/dependabot.yml
This combines go pkg updates in to a weekly branch, saving bother and rebase time.
=> dependabot: batch updates

.golangci.yml, libcni/conf.go, pkg/invoke/exec.go, plugins/test/noop/main.go
Signed-off-by: Matthieu MOREL <matthieu.morel35@gmail.com>
=> enable gocritic linter

.github/workflows/test.yaml, Makefile, mk/dependencies/golangci.sh, mk/lint.mk, test.sh
As govet and gofmt are now handled by golangci-lint, there is no need to apply them here.
Signed-off-by: Matthieu MOREL <matthieu.morel35@gmail.com>
=> Define Makefile with golangci-lint

README.md
Add aws-vpc-cni-k8s CNI plugin to 3P list. aws-vpc-cni-k8s is a default CNI plugin on EKS.
About the plugin - https://github.com/aws/amazon-vpc-cni-k8s/blob/master/docs/cni-proposal.md
=> Add AWS VPC CNI for 3P list

SPEC.md
fixed misspelled 'comand' to 'command'
=> SPEC: fix misspelled word

CODE-OF-CONDUCT.md, CONTRIBUTING.md, CONVENTIONS.md, Documentation/spec-upgrades.md, RELEASING.md, libcni/api.go, pkg/skel/skel_test.go, pkg/types/types.go
Go through and update some incorrect / obsolete links and references.
No code changes.
Fixes: #946
=> cleanup: update references, make links relative

SPEC.md, pkg/types/types.go, pkg/types/types_test.go
Extend route attributes to make route selection available based on route priority and enable per-route MTU settings.
It's will be helpfull in multi-CNI environment, and networks, that support jumbo-frame.
Fixes: #1004
=> Add route attributes - MTU, AdvMSS, Priority

libcni/api_test.go, pkg/types/100/types.go, pkg/types/types.go
This change fix to avoid empty DNS/IPAM field in NetConf/Result if DNS is empty.
=> Add Marshal function in Result/NetConf to omit empty value

SPEC.md, pkg/types/100/types.go, pkg/types/100/types_test.go, pkg/types/types_test.go, pkg/version/version_test.go
=> Add SocketPath/PciID to Interface struct 

SPEC.md, pkg/types/types.go, pkg/types/types_test.go
=> Add table ID property for routes

libcni/api.go, libcni/api_test.go
Fixes: #1055
Closes: #1066
In `DelNetworkList` function, ignore the errors returned by `getCachedResult` and continue to invoke plugins for deletion as best effort. Also updated the test case to adapt this new behavior.
Cached results are deleted from disk in the following two cases:
1. `getCachedResult` returns an error; OR
2. `getCachedResult` succeeds and no errors are returned from plugins
Cached results are not deleted if (I think this will allow clients to retry the deletion)
1. `getCachedResult` succeeds AND 
2. Plugin fails
=> tolerate invalid cni caches for deletion

SPEC.md, pkg/types/100/types.go, pkg/types/100/types_test.go
This commit allow CNIs to expose the MTU of interface
=> Add MTU to CNI result

libcni/api.go, libcni/api_test.go, pkg/invoke/delegate.go, pkg/invoke/delegate_test.go, pkg/types/types.go
A few small things I discovered I needed while implementing spec v1.1 for the plugins.
=> Minor CNI v1.1 api fixes

libcni/api.go
When looking at how to integrate STATUS/GC in containerd I noticed that Version was not exposed on the CNI Interface. I am not certain if that was intended? I didn't add a test for this yet since it might be intentionally not added. This would be helpful to have in CNI 1.1.
=> Add Version to CNI interface

.github/workflows/test.yaml, mk/dependencies/golangci.sh
New golangci-lint version is available.
This change updates golangci-lint in CI to v1.57.1.
Lint check passes
=> Update golangci-lint to v1.57.1

SPEC.md, libcni/api.go, libcni/api_test.go, libcni/conf.go, libcni/conf_test.go, pkg/types/types.go
This allows administrators to disable garbage collection in exceptional circumstances, such as multiple runtimes sharing a network configuration.
=> Spec, libcni: add disableGC flag

pkg/types/types.go
=> Fix faulty json.Marshal behavior for embeds types.NetConf

go.mod, go.sum, libcni/conf.go, pkg/version/plugin.go, pkg/version/version_test.go
We didn't really need it, and it's yet another dep to update.
=> libcni: remove use of Masterminds/semver

SPEC.md, libcni/api.go
The SPEC said valid attachments should be `cni.dev/attachments`, whereas libcni used `cni.dev/valid-attachments`. Oops.
This changes the SPEC to match libcni, *and* has libcni set both variables, just in case.
Fixes: #1101
=> SPEC, libcni: harmonize GC valid-attachment key

SPEC.md, cnitool/cnitool.go, libcni/api.go, libcni/api_test.go, libcni/conf.go, libcni/conf_test.go, pkg/types/types.go, pkg/version/version.go, pkg/version/version_test.go, plugins/test/noop/main.go
Designed to address https://github.com/containernetworking/cni/issues/928 (and related issues such as https://github.com/containernetworking/cni/issues/878), largely building off the ideas in #928.
The basic problem is that since plugin config is stored in a centralized, non-locked config file on the node, if multiple node agents install or remove CNI plugins in the same chain, they are both mutating a shared node resource with no locking, which unavoidably leads to unfixable TOCTOU errors.
This resolves that by moving the plugin configs out of the main shared node config, and into subdirectories, Unix init-system style.
~One thing that is TBD is whether we rev the network config object spec for this or not.~
- ~#928 describes a mechanism where the subdir-based loading is dynamic and not …
=> RFC - Support safe subdirectory-based plugin conf loading

libcni/api.go, libcni/conf.go, pkg/types/types.go
We were a bit over-eager with the deprecations; these types and aliases are doing no harm :-).
=> libcni: remove some deprecation warnings

README.md
Some of the 3rd party plugins in the README are archived. This PR removes them
=> docs: remove archived 3rd party plugins

SPEC.md, pkg/types/types.go
This PR adds constants for STATUS error codes 50 and 51 so plugins can import them. It also fixes a broken link to the spec document.
=> Add error codes for STATUS verb to `types.go` and `SPEC.md`
